### ISSUE TITLE
Implement a prop that blocks the selection of dates

### ISSUE THREAD

**Issue by ameriles** [shahabyazdi/react-multi-date-picker#1]
Will be great to have the possibility to block the selection of out of scope dates, in a similar way that [react-datepicker](https://reactdatepicker.com/) has.

- minDate
- maxDate

This way we could block the user the selection of dates outside the specified range (Very useful when you want to avoid the user picks a date in the past).

**Comment by shahabyazdi** [comment]
Good idea..
Thanks for mention it. I will work on that tomorrow

**Comment by shahabyazdi** [comment]
Your suggested feature is added to demo page(not master) , please check it out at https://shahabyazdi.github.io/react-multi-date-picker/#min-&-max-date and let me know if its ok.

**Comment by shahabyazdi** [comment]
27f475f5c6e4568321b16f469e4058bb97ad94d6

**Comment by ameriles** [comment]
Awesome stuff. Thanks!

**Comment by shahabyazdi** [comment]
you're welcome
