### ISSUE TITLE
The current 2.0.0 version DatePicker is not working. 

### ISSUE THREAD

**Issue by Abhi1597** [shahabyazdi/react-multi-date-picker#10]
Getting 
![Screenshot from 2021-01-06 15-12-46](https://user-images.githubusercontent.com/56822909/103753972-b8dc5880-5031-11eb-9302-9121c68f7556.png)
Uncaught TypeError: r.setLocal is not a function.

I tried the 1.9.0 version, even that is not working. Please upload only working versions or something that doesn't break the old version.

**Comment by shahabyazdi** [comment]
Did you manually upgrade the react-date-object to a version higher than 1.1.8?
If not, you shouldn't have such a problem.

https://codesandbox.io/embed/react-multi-date-picker-ffgdn?codemirror=1

**Comment by Abhi1597** [comment]
Do I need to use the react-date-object dependency, I was doing it with new Date().

**Comment by shahabyazdi** [comment]
If you are using browser mode change the 
date-object@latest to date-object@1.1.8:
```javascript
<script src="https://cdn.jsdelivr.net/npm/date-object@1.1.8/dist/date-object.min.js"></script>
```

**Comment by shahabyazdi** [comment]
> Do I need to use the react-date-object dependency, I was doing it with new Date().

If you are using browser mode , you need to add date-object dependency . If you are using react-app the react-date-object is installed with package

**Comment by andrejastanojkovic** [comment]
I can't open the date picker in any way, I keep getting that error.
And I don't use a date object at all

**Comment by andrejastanojkovic** [comment]
Even if I downgrade the package version, it is not possible to use datepicker.
Do you have any idea how I can fix that error, my app is blocked for users now

**Comment by shahabyazdi** [comment]
There should'nt be a problem at all !
I recently released 2.0.1 please upgrade , the problem will be fixed.

**Comment by shahabyazdi** [comment]
```
npm uninstall react-multi-date-picker react-date-object
npm install react-multi-date-picker@2.0.1
```

**Comment by andrejastanojkovic** [comment]
Thanks a lot, now it works!

**Comment by Abhi1597** [comment]
Yeah it's working now, I had to downgrade to @1.0.0. Thanks
