### ISSUE TITLE
numberOfMonths shows future months even when that is over the maxDate

### ISSUE THREAD

**Issue by dzsodzso63** [shahabyazdi/react-multi-date-picker#107]
I need a range picker to select the last N days, showing history.
If I set up the picker like this:
```
<DatePicker
    range
    maxDate={new Date()}
    value={values}
    numberOfMonths={2}
/>
```
With the default values (`[]`), it will show the current month and the next month, but I think it should show the previous month and the current one, since the next month is after the maxDate

**Comment by shahabyazdi** [comment]
Hi, you need to use `currentDate` prop:
