### ISSUE TITLE
Customize date style when they're deactive and range

### ISSUE THREAD

**Issue by adhiardiansyah** [shahabyazdi/react-multi-date-picker#111]
Hi,
Is it possible to customize date range style when they're deactive and actually they're in range?
For example
![Screenshot from 2022-05-20 17-42-37](https://user-images.githubusercontent.com/62105624/169511797-da4e043a-e2dc-4b42-9699-68227b11f00a.png)

I wanna change 1-6 August 2022 in July month and 31 July 2022 in August month's background color to orange because they're still in range

Thanks in advance.

**Comment by shahabyazdi** [comment]
Hi
You can use part of this sandbox for your work.
https://codesandbox.io/s/disable-dates-in-range-mode-jpjn82?file=/src/App.js

**Comment by adhiardiansyah** [comment]
> Hi You can use part of this sandbox for your work. https://codesandbox.io/s/disable-dates-in-range-mode-jpjn82?file=/src/App.js

I tried but still cannot when `numberOfMonths={2}` any another way?

**Comment by adhiardiansyah** [comment]
I finally found the solution using `mapDays`. Thanks for the help
