### ISSUE TITLE
Not able to remove comma(",") in between month and year.

### ISSUE THREAD

**Issue by sharan98727** [shahabyazdi/react-multi-date-picker#116]
I want to remove the , after month in calendar or date picker. for example in calendar it is showing month with year as June, 2022. I do not want "," between them, I want to display it as June 2022. How could this be done.

**Comment by jamsfy-cyrus** [comment]
It cannot be done so far

We need a escape hatch to manually render header contents (feature request)

**Comment by bsinoimeri** [comment]
+1

**Comment by shahabyazdi** [comment]
I'm working on it.

**Comment by bsinoimeri** [comment]
Do you have an estimation when this will be live? Thanks a lot 🥇

**Comment by shahabyazdi** [comment]
It may take a few days.

**Comment by shahabyazdi** [comment]
@belandrio You can now edit the separator between month and year in the header with the monthYearSeparator prop.
https://shahabyazdi.github.io/react-multi-date-picker/header/#separator-between-month-&-year
