### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by Moinax** [shahabyazdi/react-multi-date-picker#128]
Hi @shahabyazdi 

I see that you did a lot of changes in the code since I installed your module a year ago and you even upgraded to a major version.

I'm currently on version 2.5.6 and I'm bit worried about upgrading to the latest version because there is no `changelog.md`, so I don't know if there is any breaking changes in the public api.

I have the feeling that you didn't do any breaking changes on the public api and only changed the internal code, but it's hard to say with the 206 file changes between the two versions :D

It would be nice and more reliable if you could create a `changelog.md` with the changes (breaking or not) between each major or minor release (if you actually follow the semver specification)

Thanks again for your awesome job.

PS. I'm a bit sad that you don't have more stars on github, but I can see that you have a good download rate on npm which is awesome :+1:

**Comment by shahabyazdi** [comment]
Hello, thank you very much for your message.
Yes, you're right, I'm so sorry I missed it.
The main changes between v2.x and v3.x are about how to import the calendars and locals (except the Gregorian calendar and English locale). and also a bit about how to define custom inputs.
[here ](https://shahabyazdi.github.io/react-multi-date-picker/v2.x/)I've kept the things that have changed in these two versions.
I will try to write a changelog for the next versions.
