### ISSUE TITLE
امکان پاک کردن اینپوت

### ISSUE THREAD

**Issue by kazem3d** [shahabyazdi/react-multi-date-picker#129]
سلام خسته نباشید 
آیا فیچری جهت پاک کردن اینپوت وجود دارد

**Comment by shahabyazdi** [comment]
سلام خوبید ؟

**Comment by kazem3d** [comment]
ممنون
منظور من در حالت نمایش به صورت موبایل اگر کاربر تاریخ را انتخاب کند و بعد
قصد داشته باشد فیلد را خالی بگذارد دیگر امکان پاک کردن تاریخ وارد شده وجود
ندارد

**Comment by shahabyazdi** [comment]
اگه بتونی مثالش رو روی کدسندباکس بزاری سعی میکنم انجامش بدم.
خیلی ممنون

**Comment by kazem3d** [comment]
https://codesandbox.io/embed/priceless-lena-mf09ov?fontsize=14&hidenavigation=1&theme=dark

**Comment by shahabyazdi** [comment]
ممنون
فکر کنم باگه و باید فیکس شه.
سعی میکنم همین امروز یا نهایتا تا فردا شب فیکسش کنم.

**Comment by kazem3d** [comment]
متشکرم از کتابخانه عالی که توسعه دادید

**Comment by shahabyazdi** [comment]
راستش رو بخوای من اومدم این رو دیباگ کنم دیدم داره کار میکنه ! اگه امکان داره شما هم یک تست کنید ببینید همونی هست که شما میخواید یا نه !
https://codesandbox.io/s/ecstatic-scott-iuzuqr?file=/src/App.js

**Comment by kazem3d** [comment]
روش خوبیه ولی اگر می‌شد دکمه ریست را داخل خود تقویم تعبیه کرد جالب میشد
ممنون

**Comment by shahabyazdi** [comment]
بزار ببینم چیکارش میشه کرد😉

**Comment by shahabyazdi** [comment]
فکر میکنم اگر نسخه 3.3.1 رو نصب کنید، این مشکل رو حل کنه.

https://shahabyazdi.github.io/react-multi-date-picker/appearance/#custom-mobile-buttons

**Comment by kazem3d** [comment]
ممنون

**Comment by shahabyazdi** [comment]
خواهش میکنم

**Comment by kazem3d** [comment]
Thanks a lot.
