### ISSUE TITLE
سلام اقای شهاب یزدی

### ISSUE THREAD

**Issue by mrsh0311** [shahabyazdi/react-multi-date-picker#13]
اقای یزدی میشه یه راهنمایی بکنید چجوری میتونم لیست شهر ها و استان ها را در ری اکت بنویسم
؟

**Comment by shahabyazdi** [comment]
<div dir="rtl">
  <p>سلام</p>
  <p>حقیقتش من اینو نوشتم ولی نمیدونم تا چه حد به کارتون بیاد :</p>
</div>

https://codesandbox.io/s/provinces--cities-rpplt?file=/src/App.js
