### ISSUE TITLE
Hover effect for date range

### ISSUE THREAD

**Issue by akashhartler** [shahabyazdi/react-multi-date-picker#133]
![calendar](https://user-images.githubusercontent.com/39995114/189834799-c52dbb85-de26-4140-9210-eff8e996949e.png)

Hi,
Thanks for the awesome plugin. Really great and easily customizable.

Is it possible to have a hover effect when the user selects the start date and moves the cursor to select the send date?

**Comment by shahabyazdi** [comment]
I will try to add this feature either next week or the week after

**Comment by shahabyazdi** [comment]
Hi.
You can enable the hover effect in range mode in v3.3.2.
https://shahabyazdi.github.io/react-multi-date-picker/range/#range-hover-effect

**Comment by akashhartler** [comment]
This is Awesome!! Thanks a lot to get this done.

Regards,

Akash Badiyani

Technical Lead Engineer //Hartley Lab

M: +91 937 3470791 <+91+937+3470791> // www.hartleylab.com

<https://twitter.com/hartleylab>
<https://www.linkedin.com/company/hartley-lab>
<https://www.facebook.com/HartleyLab/>
<https://www.youtube.com/channel/UC2wvPee8Zuu_JXjfD2sdXGA>

**Comment by akashhartler** [comment]
It would be great if you can also get that vertical scrolling for mobile.
That will make the plugin super user-friendly and fully responsive.

Regads,

Akash Badiyani

Technical Lead Engineer //Hartley Lab

M: +91 937 3470791 <+91+937+3470791> // www.hartleylab.com

<https://twitter.com/hartleylab>
<https://www.linkedin.com/company/hartley-lab>
<https://www.facebook.com/HartleyLab/>
<https://www.youtube.com/channel/UC2wvPee8Zuu_JXjfD2sdXGA>

**Comment by vinesh20** [comment]
@shahabyazdi I was just trying to implement rangeHover effect last week and today I noticed new prop in the website. 

Then I realized there is a new package v3.3.0 released which already has the changes. Thanks for the new update! I am removing my changes to be in sync with your code.

**Comment by vinesh20** [comment]
@shahabyazdi  Please update index.d.ts file with rangeHover prop in CalendarProps interface. I think it is not updated in 3.3.3 version and failing in typescript projects.

**Comment by shahabyazdi** [comment]
> @shahabyazdi Please update index.d.ts file with rangeHover prop in CalendarProps interface. I think it is not updated in 3.3.3 version and failing in typescript projects.

done!
