### ISSUE TITLE
Bug - Number of Months props doesn't render previous months

### ISSUE THREAD

**Issue by akashhartler** [shahabyazdi/react-multi-date-picker#135]
Hello Shahabyazdi,

I found that if we pass the Number of months props, the picker takes the current month as of the selected date month. For eg., if I have selected a range of 11th Nov 2022 to 18th Nov 2022, then the picker will only render months from Nov. Technically it should render from the current month and not the selected dates.

If you can fix this at the earliest, it would be really helpful.

**Comment by shahabyazdi** [comment]
Hi 
Please see this URL and let me know if it's work or not.
https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#opening-calendar-on-the-specified-date

**Comment by shahabyazdi** [comment]
Please try this and if it's not what you want, please modify it to show the bug.
https://codesandbox.io/s/vigilant-hooks-d9sd56?file=/src/App.js
