### ISSUE TITLE
Initial time

### ISSUE THREAD

**Issue by perfeshnal** [shahabyazdi/react-multi-date-picker#137]
Hello
Thanks for making such a great component.
how can i load Initial just time when I use TimePicker plugin?
I have just string time like (10:22) no date

**Comment by shahabyazdi** [comment]
I had already prepared this example.
It may be useful for you too:
https://codesandbox.io/s/crazy-rubin-2vdpbr?file=/src/App.js

**Comment by perfeshnal** [comment]
Thank you very much
