### ISSUE TITLE
Combine multiple and range calendar

### ISSUE THREAD

**Issue by hagealex** [shahabyazdi/react-multi-date-picker#138]
Hello everyone,

I'm curious if it is possible to combine the multiple with range setting. Basically my idea is to be able to select multiple date ranges.

So far, when I add both settings like this: `<Calendar className="rmdp-mobile" value={dates} onChange={setDates} multiple range locale={german_de} format={"DD.MM.YYYY"} weekStartDayIndex={1} />`

I get the range mode, but no multiselect.

Is this possible somehow or would this be a new feature?

Kind regards,
Alex

**Comment by shahabyazdi** [comment]
@hagealex @pete1019 multiple range picker is available in v4.0.0.
https://shahabyazdi.github.io/react-multi-date-picker/multiple-range/
