### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by vinesh20** [shahabyazdi/react-multi-date-picker#139]
Thanks for the wonderful component!

I am wondering if the component has keyboard accessibility feature built in. if it is already available, please guide me how to enable this.

**Comment by rkaufman13** [comment]
Seconding this

**Comment by rkaufman13** [comment]
I have managed to make the main calendar and the date panel plugin keyboard accessible. (Those are the components of this component that I'm using in my own project). Though  it does not encompass the entire component, would you accept a PR for this, @shahabyazdi ?

**Comment by shahabyazdi** [comment]
Of course
I would really appreciate it

**Comment by AndresSalomonMidas** [comment]
We need this change! 🙏🙏

**Comment by vinesh20** [comment]
@shahabyazdi  thank you for the effort! I didn't get a chance to test this the new update. Busy with another proj right now. I will let you know once I get a chance to test it.

**Comment by shahabyazdi** [comment]
Please reopen this if it doesn't work.
