### ISSUE TITLE
Disabling highlight for today's date

### ISSUE THREAD

**Issue by jonarnarbriem** [shahabyazdi/react-multi-date-picker#145]
When I open the date picker it automatically highlights today's date with a different color (see Oct 19. in pic below). Is it possible to remove this highlighting?

![image](https://user-images.githubusercontent.com/107482569/196710545-bf3ee449-1eb5-4aa9-ac8e-1aa00235bd60.png)

I've considered overriding the css styles for the rmdp-today class but that seems like a risky option and easy to get wrong. I also saw this post https://github.com/shahabyazdi/react-multi-date-picker/issues/124 but I tried setting onOpenPickNewDate to false and didn't notice any effect? Maybe I misunderstood their issue/question.

Edit: Ideally this would work for both the datepicker and calendar versions

**Comment by shahabyazdi** [comment]
You can disable it with CSS, see #121

onOpenPickNewDate prop is useful if you want to open the calendar without picking the current date.

**Comment by jonarnarbriem** [comment]
Yes I had considered that but then I'd need to overwrite every single css property assigned to the rmdp-today class. For example the solution mentioned in that issue doesn't mention :hover properties. If you can confirm that the only css properties assigned to the rmdp-today class are the color for normal state and :hover state then I can override those specifically. 

I'm also unsure if the rmdp-today class has any functional meaning but I doubt it does?

**Comment by shahabyazdi** [comment]
You can do it now by installing v4.0.0 and setting `highlightToday` to false.
https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#disabling-today-highlight
