### ISSUE TITLE
In the range mode, the input field is not editable

### ISSUE THREAD

**Issue by vinesh20** [shahabyazdi/react-multi-date-picker#147]
@shahabyazdi  In the range mode, the input field is not editable. It would be awesome if the input field is editable to allow users to change using keyboard.  Please kindly let me know if there is any such plan in the pipeline.

I am hacking the code to make it editable. But it looks like change are pretty complex to accomplish this.

Appreciate if you have any insight on this!

**Comment by shahabyazdi** [comment]
As you mentioned, in multiple and range modes, managing the change of dates entered by the user in the input is very complicated and requires validation. that's why I disabled it.
Currently, I am in the process of making some changes and updates in the 'develop' branch, I will definitely work on it and let you know if it is possible or not.

**Comment by vinesh20** [comment]
@shahabyazdi Awesome! thanks for the response! 

I understand that multiple mode is free style selection. It would be great if at least make the field editable in range mode. In the custom render input we can control the validation and trigger handleValueChange only after it passed through all the validation.

**Comment by shahabyazdi** [comment]
Since I added a possibility in the onChange method to validate the date for V4.0.0, the input is now editable for all modes (single, range & multiple).

**Comment by vinesh20** [comment]
@shahabyazdi  Thanks for the update! I have added custom render that overrode all the props to make it editable. I will check your changes and go with whichever is easier to maintain.

**Comment by vinesh20** [comment]
@shahabyazdi  Not a big thing. In the latest type declaration, `dateSeparator `and `multipleRangeSeparator `are defined as boolean. 

Is that the expected behavior? 

`   onChange?(
      selectedDates: DateObject | DateObject[] | null,
      validatedValue: string | Array<string>,
      input: HTMLElement,
      isTyping: boolean
    ): void | false;
    dateSeparator?: boolean;
    multipleRangeSeparator?: boolean;`

If I set the boolean, it renders 'true' string based on the following condition in `date_picker.js`. I can change in my local to repo to string. Just want to be sure, if this is the intent.

` separator = dateSeparator || (range || weekPicker ? " ~ " : ", "),`

**Comment by Schum123** [comment]
@shahabyazdi When will V4.0.0 be out? :)
@vinesh20 Would you share your code?

**Comment by vinesh20** [comment]
@Schum123 I forked V4.0.0 code and published to our internal npm registry and using it from there. There are few bugs there as I reported above. They are minor ones and you can publish on your own after fixing it. Not sure when v4.0.0 is going to be released.

Unfortunately, I can't share the code. Because, my changes are very much intertwined with our code base. Sorry about that!

**Comment by shahabyazdi** [comment]
> dateSeparator?: boolean; multipleRangeSeparator?: boolean;

Both the `dateSeparator` & `multipleRangeSeparator` have a `string` type and their default value is `~ for range` and `, for multiple mode` and `,`

**Comment by shahabyazdi** [comment]
The input is now editable in multiple and range modeds.
