### ISSUE TITLE
no year wanted

### ISSUE THREAD

**Issue by pete1019** [shahabyazdi/react-multi-date-picker#148]
Hi, thanks a lot for your date picker! So much work.

What i need:
i don't want no year to be shown. Not when i pick it and not in the Panel. Just 1. January till 31. December chooseable.
For Multidate and Range.

How is that possible?

Thanks a lot!

**Comment by shahabyazdi** [comment]
Hi and thank you!
Is this what you are looking for?
https://codesandbox.io/s/confident-bohr-s1p0mb?file=/src/App.js

**Comment by pete1019** [comment]
Awesome. Where to buy you a coffee?

**Comment by shahabyazdi** [comment]
You're Welcome!

**Comment by shahabyazdi** [comment]
for range mode. just remove multiple prop and use range prop

```javascript
import DatePicker, { DateObject } from "react-multi-date-picker";
import DatePanel from "react-multi-date-picker/plugins/date_panel";

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <DatePicker
        hideYear
        range
        format="D MMMM"
        minDate={new DateObject().toFirstOfYear()}
        maxDate={new DateObject().toLastOfYear()}
        plugins={[<DatePanel />]}
      />
    </div>
  );

```

**Comment by pete1019** [comment]
> for range mode. just remove multiple prop and use range prop
> 
> ```js
> import DatePicker, { DateObject } from "react-multi-date-picker";
> import DatePanel from "react-multi-date-picker/plugins/date_panel";
> 
> export default function App() {
>   return (
>     <div className="App">
>       <h1>Hello CodeSandbox</h1>
>       <DatePicker
>         hideYear
>         range
>         format="D MMMM"
>         minDate={new DateObject().toFirstOfYear()}
>         maxDate={new DateObject().toLastOfYear()}
>         plugins={[<DatePanel />]}
>       />
>     </div>
>   );
> ```

Thanks a lot! That really helped.

Did you get my e-mail an will reply?

BR
