### ISSUE TITLE
How can I style the datepicker box (ex: width and height) and how to show full name of week days? شنبه، یکشنبه، ...

### ISSUE THREAD

**Issue by ali-mozaffari** [shahabyazdi/react-multi-date-picker#149]

**Comment by shahabyazdi** [comment]
You can name the days of the week using the [weekDays ](https://shahabyazdi.github.io/react-multi-date-picker/fa/locales/#%D9%85%D8%B4%D8%AE%D8%B5-%DA%A9%D8%B1%D8%AF%D9%86-%D8%B1%D9%88%D8%B2%D9%87%D8%A7%DB%8C-%D9%87%D9%81%D8%AA%D9%87-%D8%AF%D9%84%D8%AE%D9%88%D8%A7%D9%87-#1) prop. And also you can render custom input by using the [render ](https://shahabyazdi.github.io/react-multi-date-picker/fa/types/#%D8%AF%D8%B3%D8%AA%DB%8C-(%DA%A9%D8%A7%D9%85%D9%BE%D9%88%D9%86%D9%86%D8%AA)) prop

**Comment by ali-mozaffari** [comment]
> You can name the days of the week using the [weekDays ](https://shahabyazdi.github.io/react-multi-date-picker/fa/locales/#%D9%85%D8%B4%D8%AE%D8%B5-%DA%A9%D8%B1%D8%AF%D9%86-%D8%B1%D9%88%D8%B2%D9%87%D8%A7%DB%8C-%D9%87%D9%81%D8%AA%D9%87-%D8%AF%D9%84%D8%AE%D9%88%D8%A7%D9%87-#1) prop. And also you can render custom input by using the [render ](https://shahabyazdi.github.io/react-multi-date-picker/fa/types/#%D8%AF%D8%B3%D8%AA%DB%8C-(%DA%A9%D8%A7%D9%85%D9%BE%D9%88%D9%86%D9%86%D8%AA)) prop

Thank you for your response.

**Comment by shahabyazdi** [comment]
You're welcome. Sorry for the late reply.
