### ISSUE TITLE
Calendar skips one month when navigating between months.

### ISSUE THREAD

**Issue by Karin-Bhandari** [shahabyazdi/react-multi-date-picker#15]
Steps to reproduce the issue:
1. Select a range of 29 days(Let say from Jan 1 to Jan 29). 
2. Then click okay.
3. Again click the calendar and try to navigate to Feb now the calendar automatically takes you to March.

Note:
1. When we select less than 29 days then we cannot reproduce the issue.

**Comment by shahabyazdi** [comment]
Thank you for reporting this bug.
The problem seems to be fixed in v2.0.7
b950e93e20616dd3a82196cac57e29ca74bb73c2
