### ISSUE TITLE
Only Days of Week possible?

### ISSUE THREAD

**Issue by pete1019** [shahabyazdi/react-multi-date-picker#150]
Hi, thanks alot again for your great work on the multi-date-picker. Love it.

How would it be possible to Multi pick and Range mode:
Only the Days of the Week?
Mon, Tue, Wed, Thur, Fri, Sat, Sun

No dates/years wanted / needed.

Thanks a bunch.

**Comment by pete1019** [comment]
@shahabyazdi 

Any idea on this?
Thanks a lot.

**Comment by shahabyazdi** [comment]
Hi.
Sorry for the late answer.
I'm afraid to say that it is not possible to select multiple days and range days with this library.
