### ISSUE TITLE
Is it possible to enable user to make specific dates clickable and disable rest of the date?

### ISSUE THREAD

**Issue by saleemshan** [shahabyazdi/react-multi-date-picker#152]
Hi, thanks alot again for your great work on the multi-date-picker. Love it.

I am using date picker with sort date option enable 
I want user to select dates from specific date given and disable rest of the dates from calendar is it possible?

Thanks a bunch.

**Comment by shahabyazdi** [comment]
Hi. sorry for the late answer!
yes, you can use map days to disable dates:
https://shahabyazdi.github.io/react-multi-date-picker/map-days/#disabling-days
