### ISSUE TITLE
Tool Tips on hover over Dates?

### ISSUE THREAD

**Issue by pete1019** [shahabyazdi/react-multi-date-picker#154]
Hi,

how to have Tool Tips on hover over Dates?

Thanks a lot!

**Comment by shahabyazdi** [comment]
Hello.
Please check [this ](https://shahabyazdi.github.io/react-multi-date-picker/map-days/#adding-tiltle-to-days)and [this ](https://shahabyazdi.github.io/react-multi-date-picker/map-days/#custom-tooltip)example and let me know if they work or not.

**Comment by pete1019** [comment]
@shahabyazdi 
Thanks a lot.

How would we add the Tooltips to certain dates?

**Comment by shahabyazdi** [comment]
I hope this would help!

**Comment by pete1019** [comment]
Thanks a lot. How to donate towards your awesome react-multi-date-picker?

**Comment by shahabyazdi** [comment]
You're very welcome. It's not necessary. I am very glad that it helped.

**Comment by pete1019** [comment]
What we need:
Assign names to a lot of Holidays.

How to do that?

Thanks again!
