### ISSUE TITLE
Bug in timepicker if number keeps being pressed 

### ISSUE THREAD

**Issue by vercamach** [shahabyazdi/react-multi-date-picker#155]
When I am typing into the timepicker input and I keep pressing a number the dates/time keep changing. 

I would expect that once I reach the maxLength it would not let me type anymore. 

https://user-images.githubusercontent.com/26543699/206456734-87bf54ce-f7b6-4f83-a720-92036cfb8701.mov

**Comment by shahabyazdi** [comment]
Thanks for reporting this bug! I will work on it!

**Comment by chiragmak10** [comment]
Hi @shahabyazdi  any update on this issue

**Comment by shahabyazdi** [comment]
Fixed in v4.0.0!
