### ISSUE TITLE
How to set two months view in range date picker

### ISSUE THREAD

**Issue by Rastiiii** [shahabyazdi/react-multi-date-picker#16]
Hi
Thanks for your perfect module. I am currently working on this module in my web application, And it's working great, but I need to show two months instead of one in range date picker.
How to display two months to selecting the range date?

Best regards

**Comment by shahabyazdi** [comment]
Hi
I apologize for the delay in sending the reply.
I will probably not be able to update for the next 3 days. After that, I will provide this possibility for you if you mean two calendars.

**Comment by Rastiiii** [comment]
Hi
I need to have a two-month view of the current month and next month in choosing the time period by date range picker.
As you can see in the image below.
![datepicker](https://user-images.githubusercontent.com/78930526/107812546-18422c80-6d85-11eb-9f02-304d31b32f7f.png)
Thank you so much

**Comment by shahabyazdi** [comment]
OK , i will do it as soon as i can get access to my pc (maximum in next two days).

**Comment by shahabyazdi** [comment]
Hello
Please install the latest version and use `numberOfMonths` prop to set the number of months you want to display in the calendar , for example:
```javascript
<DatePicker
   range
   numberOfMonths={2}
/>
```

Please let me know if it works or not .

**Comment by Rastiiii** [comment]
Hello Mr. Yazdi
It works properly.
Thanks a lot.

**Comment by shahabyazdi** [comment]
You're welcome.
