### ISSUE TITLE
Bug in timepicker - cannot edit time input field in Portal mode

### ISSUE THREAD

**Issue by hzbarkan** [shahabyazdi/react-multi-date-picker#164]
When i am using TimePicker plugin inside DatePicker that is in Portal mode, the hour and minute cannot be edited by clicking the textfield and type it, it can only be changed by clicking the up/down arrow.

I expected the input field to be working in both normal and portal modes. Thanks for your support.

**Comment by shahabyazdi** [comment]
I can't reproduce the bug you mentioned.
Please see this sandbox and let me know if it works or not.
https://codesandbox.io/s/timepicker-3c2bik
