### ISSUE TITLE
How to add "Cancel" and "OK" button like the mobile mode, but in normal/prime mode?

### ISSUE THREAD

**Issue by hzbarkan** [shahabyazdi/react-multi-date-picker#165]
Hi, i would like to ask if there's a way to enable the Cancel and OK button toolbars like the mobile theme in the non-mobile theme? Thanks for your work and support in this library.

**Comment by shahabyazdi** [comment]
Maybe this plugin or its customized one can be suitable for your case.
https://shahabyazdi.github.io/react-multi-date-picker/plugins/toolbar/
Also, you can add your desired elements as children to the DatePicker:
https://shahabyazdi.github.io/react-multi-date-picker/children/
