### ISSUE TITLE
disabled mode in css not working 

### ISSUE THREAD

**Issue by AmirrezaAsadpour** [shahabyazdi/react-multi-date-picker#168]
hi ,  I want give my style for disabled mode in css like this :

  .rmdp-input:disabled , input.rmdp-input:disabled  , button.rmdp-button:disabled  {
    font-family: Yekan ;
    padding: 0px 5px;
    border-radius: 4px;
    border: 1px solid #d9d9d9 ;
    background: #f5f5f5;
    cursor: not-allowed;
    opacity: 1;
    pointer-events: none;
  }

but it's not working , what should I do ?
thank you

**Comment by shahabyazdi** [comment]
It seems to work.
I set the red background color to your style to ensure that it works
You can see the example from this URL:
https://codesandbox.io/s/priceless-glitter-l5hf6q?file=/src/styles.css

**Comment by AmirrezaAsadpour** [comment]
thank you for your answer , but when i use 
render={<InputIcon />}
the disabled mode not working . 
what should i do for this case ?

**Comment by AmirrezaAsadpour** [comment]
> 

sorry again , and i need to change placeholder color , what is the class ?

**Comment by shahabyazdi** [comment]
If you are using the `render` prop, then you don't need the `disable` prop at all!
You can directly pass your desired classes and props (such as placeholder) to your custom input.
