### ISSUE TITLE
currentDate Goes back to today's date when useing backspace/delete

### ISSUE THREAD

**Issue by Sarvenaz-s** [shahabyazdi/react-multi-date-picker#169]
Hi, 
there is no onlyDay calendar. so with 
{ disableYearPicker ,  disableMonthPicker ,   hideYear ,  hideMonth } property, 
I was able to show only day calendar to user.
but if the day is deleted via keyboard. the day goes back to current date. 
for example if I set Currentdate to "فرودین 1401"  like this : 
    <DatePicker
          value={day}
          disableYearPicker
          disableMonthPicker
          hideYear
          hideMonth
          format="DD"
          // animations={[
          //    transition({
          //       from: 35,
          //       transition:
          //          "all 400ms cubic-bezier(0.335, 0.010, 0.030, 1.360)",
          //    }),
          // ]}
          currentDate={
                  new DateObject({ calendar: persian })
                  .set("month", 01)
                  .set("year", 1401)
          }
          calendar={persian}
          locale={persian_fa}
          calendarPosition="bottom-right"
          color="primary"
          onChange={(e) => handleChangeDay(e)}
          name={dayName || day}
          render={
           <TextField
         {...props}
         label={label}
         onFocus={openCalendar}
         value={stringDate}
         onChange={inputChangeHandler}
         InputProps={{
            autoComplete: "off",
            startAdornment: (
               <InputAdornment position='start'>
                  <EventIcon color='primary' />
               </InputAdornment>
            ),
         }}
      />
          }
        />

if I delete the data in TextField it goes back to "30 بهمن ".
then if I choose 31 farvardin , the day value is saved 1 esfand.

**Comment by shahabyazdi** [comment]
Hi
The problem you mentioned is probably due to the wrong definition of custom input.
I modified it in the code sandbox and everything seems to be ok.
Please check it and let me know if there is any problem.
https://codesandbox.io/s/confident-snow-hy4bsi?file=/src/App.js

**Comment by shahabyazdi** [comment]
Regarding the date of Farvardin 31st, I have to inform you that you had chosen the date of Bahman 31st, and since there is no Bahman 31st, the selected date will be changed to Esfand 1st.
Please comment the hideMonth prop to see the result.

**Comment by Sarvenaz-s** [comment]
Thank you for your response. but I don't want to show month , I only want to show day. that's why if I hide month and change the day number, it shows 1 of esfand. is there any way around it?

**Comment by shahabyazdi** [comment]
Yes, you can hide the month in the above example
I only raised that issue for the test.
https://codesandbox.io/s/confident-snow-hy4bsi?file=/src/App.js

**Comment by Sarvenaz-s** [comment]
Shahab, I saw that you added dateObject and set month and year for default value date, what I do is that I get year and month values from only year and only month calendar, then I set that inside only day calendar, so some thing like this: 
function BirthdayDatePiker({
  year,
  yearError,
  yTitle,
  handleChangeYear,
  yearHelperText,
  yearName,

  month,
  monthError,
  mTitle,
  handleChangeMonth,
  monthName,
  monthHelperText,

  day,
  dayError,
  dTitle,
  handleChangeDay,
  dayName,
  dayHelperText,

  ...props
}) {
  const dateObject = new DateObject({ calendar: persian });

  return (
    <>
      {/* Y E A R    P I C K E R */}
      <Box sx={{ mx: 1, width: 100 }}>
        <DatePicker
          value={year}
          onlyYearPicker
          format="YYYY"
          // animations={[
          //    transition({
          //       from: 35,
          //       transition:
          //          "all 400ms cubic-bezier(0.335, 0.010, 0.030, 1.360)",
          //    }),
          // ]}
          calendar={persian}
          locale={persian_fa}
          calendarPosition="bottom-right"
          color="primary"
          onChange={handleChangeYear}
          minDate={new DateObject({ calendar: persian }).set("year", 1300)}
          maxDate={new DateObject()
            .setCalendar(persian)
            .setFormat("YYYY")
            .parse()
            .format()}
          name={yearName || year}
          render={
            <CustomInput
              label={yTitle || "سال تولد"}
              required
              helperText={yearHelperText}
              inputProps={{ maxLength: 4 }}
            />
          }
        />
        {yearHelperText ? (
          <FormHelperText sx={helperStyle}>سال را وارد کنید.</FormHelperText>
        ) : null}
      </Box>

      {/* M O N T H    P I C K E R */}
      <Box sx={{ mx: 1, width: 100 }}>
        <DatePicker
          value={month}
          onlyMonthPicker
          disableYearPicker
          hideYear
          format="MM"
          // animations={[
          //    transition({
          //       from: 35,
          //       transition:
          //          "all 400ms cubic-bezier(0.335, 0.010, 0.030, 1.360)",
          //    }),
          // ]}
          calendar={persian}
          locale={persian_fa}
          calendarPosition="bottom-right"
          color="primary"
          onChange={handleChangeMonth}
          name={yearName || year}
          render={
            <CustomInput
              label={mTitle || "ماه تولد"}
              required
              helperText={monthHelperText}
              inputProps={{ maxLength: 2 }}
            />
          }
        />
        {monthHelperText ? (
          <FormHelperText sx={helperStyle}>ماه را وارد کنید.</FormHelperText>
        ) : null}
      </Box>

      {/* D A Y    P I C K E R */}
      <Box
        sx={{
          mx: 1,
          width: 100,
          "& .rmdp-header": {
            display: "none",
          },
        }}
      >
        <DatePicker
          value={day}
          disableYearPicker
          disableMonthPicker
          hideYear
          // hideMonth
          format="DD"
          // animations={[
          //    transition({
          //       from: 35,
          //       transition:
          //          "all 400ms cubic-bezier(0.335, 0.010, 0.030, 1.360)",
          //    }),
          // ]}
          currentDate={
            month && year
              ? dateObject
                  .set("month", month?.month?.number)
                  .set("year", year?.year)
              : new DateObject({ calendar: persian })
          }
          calendar={persian}
          locale={persian_fa}
          calendarPosition="bottom-right"
          color="primary"
          onChange={(e) => handleChangeDay(e)}
          name={dayName || day}
          render={
            <CustomInput
              label={dTitle || "روز تولد"}
              required
              helperText={dayHelperText}
              inputProps={{ maxLength: 2 }}
            />
          }
        />
        {dayHelperText ? (
          <FormHelperText sx={helperStyle}>روز را وارد کنید.</FormHelperText>
        ) : null}
      </Box>
    </>
  );
}

export default memo(BirthdayDatePiker);

and i can see 31 farvardin when i open the calendar , but when I try to type inside the textField it shows today's date which is in bahman, and since there is no 31 bahman it goes to 1 esfand. 
so my problem is when i'm trying to type 31 not pick 31.

**Comment by shahabyazdi** [comment]
As I understand, you want to get the date values separately with different inputs from the user.

Since we need three values of `day`, `month`, and `year` to parse a valid `date`, and you take them separately and independently from the user, the date will not be parsed correctly.

To solve this problem, you need to connect these three components together. I modified the example above to fix the problem.

Please see the example again and let me know if it solves your problem or not.
https://codesandbox.io/s/confident-snow-hy4bsi?file=/src/DatePicker.js

**Comment by Sarvenaz-s** [comment]
Thank you!! that actually was what I was looking for :)
