### ISSUE TITLE
DatePanel not working along with multiple selection

### ISSUE THREAD

**Issue by orlando-rojas** [shahabyazdi/react-multi-date-picker#17]
Hi, I have this component 

`<Calendar
              onlyShowInRangeDates={true}
              minDate={new Date()}
              value={selectedDates}
              onChange={setSelectedDates}
              plugins={[<DatePanel />]}
              multiple
              sort
            >`
            
And it's crashing with the following output
`Uncaught TypeError: (P || O).map is not a function`
`The above error occurred in the <E> component:`

It stops crashing if y delete either the plugin or multiple prop

**Comment by shahabyazdi** [comment]
Hi
Can you explain more in detail about the crash, for example; 
- what is the initial value (selectedDates) ?  is that an empty array or something else ?
-  when does the crash happen (from the very start or when a date is selected)?
- which version do you use ? 

I created[ this sandbox](https://codesandbox.io/s/determined-forest-4i55w?file=/src/App.js) based on code you put in you're comment and unfortunately I couldn't get the crash, so I would be grateful if you could modify it in a way that the crash is happend.
Thank you
