### ISSUE TITLE
Datepicker not converting into Italian calendar format

### ISSUE THREAD

**Issue by PradipKushare** [shahabyazdi/react-multi-date-picker#171]
Hello all, I have used react-multi-date-picker for my project and I am using multiple mode. For this I have to use Italian calendar when my language is Italian. I was tried with locale="it" but it is not working. After research, I got one solution which is, create js file which contain Italian months, weekdays numbers and meridiems. Also I had given reference for react-date-object. In that various types of the locale js files created.  created same and tried to pass it to DatePicker but it showing me wrong output. 
Actually, calendar is converting well but date is set to wrong days.

Here is the my App.js file for DatePicker

```
import DatePicker from "react-multi-date-picker";
import DatePanel from "react-multi-date-picker/plugins/date_panel";
import italian_it from './italianCalendar';
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <DatePicker
          locale={italian_it}
          multiple
          format="DD/MM/YYYY"
          plugins={[<DatePanel />]}
        />
      </header>
    </div>
  );
}

export default App;
```

My italianCalendar file is as below

`module.exports = {
  name: "italian_it",
  months: [
    ["gennaio", "gennaio"],
    ["febbraio", "febbraio"],
    ["marzo", "marzo"],
    ["aprile", "aprile"],
    ["maggio", "maggio"],
    ["giugno", "giugno"],
    ["luglio", "luglio"],
    ["agosto", "agosto"],
    ["settembre", "settembre"],
    ["ottobre", "ottobre"],
    ["novembre", "novembre"],
    ["dicembre", "dicembre"],
  ],
  weekDays: [
    ["domenica", "dom"],
    ["lunedì", "lun"], 
    ["martedì", "mar"],
    ["mercoledì", "mer"],
    ["giovedì", "gio"],
    ["venerdì", "ven"],
    ["sabato", "sab"]],
  digits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
  meridiems: [
    ["am", "am"],
    ["pm", "pm"],
  ],  
};
`

**Comment by shahabyazdi** [comment]
I just copied and pasted your locale into CodeSandbox and didn't see any issues in the days.

can take a screenshot from your component?

<img src="https://user-images.githubusercontent.com/18695593/222189939-8459b78e-c2b8-4cb4-a8d1-942f35869707.png" width="300">

https://codesandbox.io/s/eloquent-firefly-n2lfyj?file=/src/App.js

**Comment by PradipKushare** [comment]
Thanks for your reply Shahab. Actually of you see in Italian calendar in your code sandbox URL, for today's date that is 1st March 2023 is Wednesday and in that calendar 1st March is appearing for Thursday(gio), instead of is should appear for Wednesday (mer).

![image](https://user-images.githubusercontent.com/29376477/222198924-28e624b1-6854-43d4-a185-f6ddc0c5e40a.png)

![image](https://user-images.githubusercontent.com/29376477/222199004-c8b00566-98f9-46c3-bbce-fb6cd86b9139.png)

**Comment by shahabyazdi** [comment]
I see...
as you may know, this library supports multiple calendars, 
regarding the fact that some of the calendars start on Saturday and end on Friday. and some others start on Sunday and end on Saturday. and since in most countries, the weekday is started on Sunday, it would be better if I wrote the locales in the way that it starts on Sunday and end on Saturday.

here I should apologize for making you in trouble.

I fixed the locale you provided in the above example, please check it and let me know if it works or not.

there are several locales in the [date-object repo](https://github.com/shahabyazdi/date-object/blob/master/locales/cjs/gregorian_en.js) that you can see them :

```javascript
module.exports = {
  name: "gregorian_en",
  months: [
    ["January", "Jan"],
    ["February", "Feb"],
    ["March", "Mar"],
    ["April", "Apr"],
    ["May", "May"],
    ["June", "Jun"],
    ["July", "Jul"],
    ["August", "Aug"],
    ["September", "Sep"],
    ["October", "Oct"],
    ["November", "Nov"],
    ["December", "Dec"],
  ],
  weekDays: [
    ["Saturday", "Sat"],
    ["Sunday", "Sun"],
    ["Monday", "Mon"],
    ["Tuesday", "Tue"],
    ["Wednesday", "Wed"],
    ["Thursday", "Thu"],
    ["Friday", "Fri"],
  ],
  digits: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
  meridiems: [
    ["AM", "am"],
    ["PM", "pm"],
  ],
};

```
