### ISSUE TITLE
add option for to show default month 

### ISSUE THREAD

**Issue by vivek-mentorange** [shahabyazdi/react-multi-date-picker#172]
if i added min date which is belongs to next month then nothing is pick able in current month then we need to show month from min date  in calendar so add option to show default month
 
i hope i explained here

**Comment by shahabyazdi** [comment]
There are some examples in the documentation that may be useful for your case.
Please read them and see if they help or not.

[Opening Calendar On The Specified Date](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#opening-calendar-on-the-specified-date)
[Manually Set Year And Month In DatePicker](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#manually-set-year-and-month-in-datepicker)
[Manually Set Year And Month In Calendar](https://shahabyazdi.github.io/react-multi-date-picker/ref/#manually-set-year-and-month-in-calendar)
