### ISSUE TITLE
disable custom date and days

### ISSUE THREAD

**Issue by DevGreyneon** [shahabyazdi/react-multi-date-picker#174]
Hello first of all thanks for your great work
i want to know how can i achieve this first i want to disable some days like i want to disable sunday and monday on each month of year
second i want to disable some dates like i want to disable 2023-03-20 is it possible?

**Comment by marcoahansen** [comment]
Hello, did you get any progress on this issue?
I am in need of the same function.

**Comment by iEbbas** [comment]
Hi I've achive this by using the mapDays={ getDisabledDayDates }

  const getDisabledDayDates = ({ date }) => {
    let wholeDate = moment.unix(date.unix);
    // Get the day of the week (0 = Sunday, 1 = Monday, etc.)
    const dayOfWeek = wholeDate.day();
    // If the day of the week is Sunday (0), disable the day

    if (checkDisableDays(dayOfWeek)) {
      return {
        disabled: true,
        hidden: false
      };
    }

    if (checkDisableDates(wholeDate.format('YYYY-MM-DD'))) {
      return {
        disabled: true,
        hidden: false
      };
    }

  }

**Comment by shahabyazdi** [comment]
Hi
There is an example available in the documentation for disabling days:
https://shahabyazdi.github.io/react-multi-date-picker/map-days/#disabling-days
