### ISSUE TITLE
Export the TypeScript typings for the props used in custom component

### ISSUE THREAD

**Issue by ianhattonieso** [shahabyazdi/react-multi-date-picker#175]
Hi there,

I'm using `render` to render a custom input component as described in the [documentation](https://shahabyazdi.github.io/react-multi-date-picker/types/#custom-(component)).

Everything is working as expected, but as I'm using TypeScript I would like to add typings to the props in my custom component. I'm currently having to using `props: any`:

`const CustomComponent: FC = (props: any) => {
  return <button onClick={props.openCalendar}>{props.value}</button>;
};`

Would it be possible for you to export the typings for the props that are used in the component that's passed to render?

Many thanks!

**Comment by shahabyazdi** [comment]
Sorry for my late reply.
I will definitely do it.

**Comment by shahabyazdi** [comment]
@ianhattonieso The CustomComponentProps type is exported in v4.0.0. please let me know if not worked.

**Comment by AlinaKuzm** [comment]
Hi!
I also have a problem with custom component. I need to add some styles and icon to input, so I added render props

        <Controller
          control={control}
          name="publicationDate"
          render={({field}) => <DatePicker
            range
            containerStyle={{width: '100%'}}
            value={field.value}
            calendarPosition="bottom"
            onChange={(date) => {
              date && setValue('publicationDate', (date as DateObject[]).map(date => new Date(date.toString()).toISOString()))
            }}
            render={
              <TextField
                {...field}
                label="Version publication date"
                InputProps={{endAdornment: <CalendarIcon/>}}/>
            }
          />}
        />

and it leads to two problems:

1) Warning: React does not recognize the `openCalendar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `opencalendar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

2) Warning: React does not recognize the `handleValueChange` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `handlevaluechange` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Can you help me please?

**Comment by ianhattonieso** [comment]
> @ianhattonieso The CustomComponentProps type is exported in v4.0.0. please let me know if not worked.

Thank you! Working nicely :)
