### ISSUE TITLE
Add transition to calendar on month change (when button is pressed)

### ISSUE THREAD

**Issue by ardalan-nhd** [shahabyazdi/react-multi-date-picker#176]
Hi. First of all thanks for the great and easy to use library.
I need to add a transition when the next or previous month buttons are clicked and the month is changing. Is there a way to achieve such behavior? You can have a look at [`@mui/x-date-pickers`](https://mui.com/x/react-date-pickers/#overview) example for clearance.
Thanks in advance.

**Comment by shahabyazdi** [comment]
I'm very sorry, but it can't be done at the moment.
