### ISSUE TITLE
Customizing the sty;es behavior of header (rmdp-header-values)

### ISSUE THREAD

**Issue by ardalan-nhd** [shahabyazdi/react-multi-date-picker#177]
Hi. I need the month and year selectors become dropdown. Something like image below. Is there a way to achieve this? Thanks in advance
![image](https://user-images.githubusercontent.com/73616143/224563772-5962c71f-516b-487c-935b-f1b3fc81f23a.png)

**Comment by shahabyazdi** [comment]
No, Unfortunately, this is not possible :(
