### ISSUE TITLE
DatePicker component onChange function does not update internal state.

### ISSUE THREAD

**Issue by schweiza88** [shahabyazdi/react-multi-date-picker#18]
Line 473, within  date_picker.js,  passes the internal state variable of "date" into the onChange user-defined function (passed in as a property); however, it fails to do anything with the function.

I wrote a function that is referenced within my onChange function definition. Below is the onChange property value, alongside the function I have created:

//Passing in fat arrow function via JSX property
onChange={(dates) => {selectLatestMonthDate(dates)}}

//onChange property will call the below function, when referenced within the DatePicker component. 
//This function allows for the selection of multiple dates, but will only allow the user to select one date per
//month - maintain the latest date selected.
 function selectLatestMonthDate(dates) {
	dates =  dates.filter(date => {
		 return dates.find(otherDate => {
			  return Number(otherDate.day) > Number(date.day)
			  && Number(otherDate.month) == Number(date.month); 
		 }) == undefined;
	});
}

I have confirmed that DatePicker is calling my function, via a reference to the onChange property, and passing in an array of DateObjects (representing days that I have selected within the DOM).  The problem is that my function, which overwrites the date array by removing some elements from the array,  is not passed to the "setDate" state mutator within DatePicker. "SetDate" is called on line 469 - before the onChange call. 

This is preventing me from modifying the date state via my onChange function. I cannot extend the behavior of multiple selection. Perhaps the "setDate" state reference can be moved to line 474, so that modifications within the onChange function are considered. This will make it very easy for developers to customize the multiple-select behavior, through onChange.  

Otherwise, if this change is not made, I see no other way of modifying the state of this "stateless" component. The only other solution, would be to move to ES6 classes.

Thanks for your help.

**Comment by shahabyazdi** [comment]
Hi
Thanks for your explanation in details.
I wrote this component in the way the user could be able to use it with or without state .
if you want to submit the user selected dates directly without modification; the stateless component is recomended, but If you want to modify the selected dates , you need to use external state and store the user selected dates after modifying it in onChange function using setState.
for example you can modify your code like this, so you can see the `selectLatestMonthDate` function works as you expect  :

```javascript
import { useState } from "react";
import DatePicker from "react-multi-date-picker";

export default function App() {
  const [values, setValues] = useState([]);

  return (
    <div className="App">
      <DatePicker 
          multiple 
          value={values} 
          onChange={selectLatestMonthDate} 
       />
    </div>
  );

  function selectLatestMonthDate(dates) {
    setValues(
      dates.filter(date => {
        return (
          dates.find(otherDate => {
            return (
              otherDate.day > date.day &&
              otherDate.month.number === date.month.number
            );
          }) === undefined
        );
      })
    );
  }
}
```

**Comment by schweiza88** [comment]
Hey:

Thank you for the quick response and code example. 

Looking through it, I can see that this is very much the React way of doing things.  Coming from a more traditional server development background, some of these front-end framework concepts are a bit foreign to me (though I have spent hours reading). Even JavaScript, beyond very simple inline <script> logic, is new to me. 

If I could bother you with one more question:

My goal (whether it is a good design pattern or not I suppose you can tell me) was to completely encapsulate React so that my application simply needs to reference a Webpack-ed bundle and that's it; No explicit React DOM rendering in my file. 

I took your code example and plugged it into my ES6 module. Instead of exporting the functional/stateless component, I want to export a function that renders the component DOM.  I have attached that module. 

What do you think? Is this some sort of anti-pattern? I will be the first to admit that I am completely obsessed with declarative abstraction (not a fan of imperative programming). for this reason, I would prefer that application developers, using my bundle, are not even aware that React is being used. I simply want the DatePicker to appear where they want it.

Thanks again!

**Comment by shahabyazdi** [comment]
> Thank you for the quick response and code example.

I'm happy to help...
First of all let me not comment on what is wrong and what is right because I'm not an expert.
back to the problem you mentioned, I [suggested a way](https://github.com/shahabyazdi/react-multi-date-picker#browser-none-react-app) to render datepicker in none react app that could be useful for you.

I modified it to work in the way you wanted. just copy and paste below code in plaint text , save it as test.html and drag it to your browser:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>React Multi Date Picker</title>
  </head>
  <body>
    <span>DatePicker Example :</span>
    <div id="datePicker"></div>

    <!-- Ract -->
    <script src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>

    <!-- DatePicker and dependencies-->
    <script src="https://cdn.jsdelivr.net/npm/date-object@latest/dist/date-object.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/react-element-popper@latest/build/browser.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/react-multi-date-picker@latest/build/browser.min.js"></script>

    <script>
      const { DatePicker } = ReactMultiDatePicker;

      function DatePickerComponent() {
        const [values, setValues] = React.useState([]);

        return React.createElement(DatePicker, {
          multiple: true,
          value: values,
          onChange: selectLatestMonthDate
        });

        function selectLatestMonthDate(dates) {
          setValues(
            dates.filter((date) => {
              return (
                dates.find((otherDate) => {
                  return (
                    otherDate.day > date.day &&
                    otherDate.month.number === date.month.number
                  );
                }) === undefined
              );
            })
          );
        }
      }

      ReactDOM.render(
        React.createElement(DatePickerComponent),
        document.getElementById("datePicker")
      );
    </script>
  </body>
</html>

```

**Comment by schweiza88** [comment]
Thank you. 

I did see this, but prefer not to go with this approach unless I absolutely find no other way. It is generally not recommended to directly reference dependency scripts via the <script> tags.  

You may close this issue, since you did provide a more appropriate way to pass state into a functional component. 

Take care!

**Comment by shahabyazdi** [comment]
Your welcome
hope you find the solution you want.
