### ISSUE TITLE
Plan to merger develop branch (v4.0.0) and bug fixes to master branch

### ISSUE THREAD

**Issue by vinesh20** [shahabyazdi/react-multi-date-picker#180]
In the develop branch, we have many changes for v4.4.0. We are using this version of code for having editable input field.

In the file calendar.js (line - 438 to 442), the below change restricting user to select year in the year picker and month in moth picker. 

`    if (selectedDate || selectedDate === null) {
      const mustUpdateState = onChange?.(selectedDate);

      if (state && mustUpdateState !== false) setState(state);
    }

`

And also, is there any plan to merge v4.0.0. into master? Please let me know if I can send a PR to merge develop branch and this bug into master to release a new version. Please confirm

**Comment by shahabyazdi** [comment]
I apologize for the delay. I will devote the entire day to reaching a favorable point with version 4.

**Comment by shahabyazdi** [comment]
Sorry for the delay.
ّFinally v4.0.0 was published on NPM!

**Comment by vinesh20** [comment]
> Sorry for the delay. ّFinally v4.0.0 was published on NPM!

Awesome! Thanks!
