### ISSUE TITLE
Unicode Problem

### ISSUE THREAD

**Issue by rahman-gitDev** [shahabyazdi/react-multi-date-picker#181]
i have problem when use 
import persian_fa from "react-date-object/locales/persian_fa"
version 3.3.4
![image](https://user-images.githubusercontent.com/90755021/232040013-80cbb337-314e-438e-a78a-01ee653c03fe.png)

**Comment by shahabyazdi** [comment]
Hi 
I can't replicate the problem you mentioned! 
Could it be a problem with the font you selected for your app?
https://codesandbox.io/s/frosty-sunset-20h5gz?file=/src/App.js

**Comment by shahabyazdi** [comment]
Can you edit the above code sandbox so that it can show the problem ? If not, please send a message to my telegram to set a google meet and discuss the matter.
