### ISSUE TITLE
portal z-index problem

### ISSUE THREAD

**Issue by pegahph** [shahabyazdi/react-multi-date-picker#184]
Hi, I am using the date picker inside a Mui dialog with a large z-index of about 1300 while the date picker popper has a 100 z-index by default and I couldn't find a solution to change it, the popper goes behind my dialog and backdrop.

I am using the portal mode

**Comment by shahabyazdi** [comment]
In the datepicker component there is a prop called `zIndex`. Have you tried it?

**Comment by smartdeveler** [comment]
I have a Mui dialog and use date picker on that but zindex not work.

**Comment by b310L** [comment]
I understand when use Mui Box such as  <Box component ={DatePicker} zIndex={200} /> , zIndex not assign to DatePicker.
use <DatePicker zIndex={200} /> to assign zIndex.

**Comment by smartdeveler** [comment]
I understand when use Mui Box such as` <Box component={DatePicker} zIndex={2000}/>` , zIndex not assign to DatePicker.
use  `<DatePicker zIndex={2000}/>`  to assign zIndex.
