### ISSUE TITLE
question: how can I scroll back to a specific date?

### ISSUE THREAD

**Issue by nilz3155** [shahabyazdi/react-multi-date-picker#185]
I want a button to position back to 'today' after going forward in months. How can I change the current showing month?

**Comment by shahabyazdi** [comment]
Please take a look at these URLs
They may be useful:

**Comment by nilz3155** [comment]
Thx, but That's not my issue. I want to change the current viewable month when the datePicker is still open.
changing "currentDate" affects after reopening.

**Comment by nilz3155** [comment]
Awesome!! Many thanks!

**Comment by shahabyazdi** [comment]
You're welcome.
