### ISSUE TITLE
Multiple onChange custom input with Timepicker (Help needed)

### ISSUE THREAD

**Issue by Schum123** [shahabyazdi/react-multi-date-picker#187]
Hi,

I'm trying to add multiple custom inputs with Datepicker and Timepicker as plugin. 

Check this [codesandbox](https://codesandbox.io/s/great-colden-ep0630?file=/src/App.js).

In the example provided it works to change the date/time with the calendar but i'm not able to add editable custom inputs.

**Comment by shahabyazdi** [comment]
I modified your example to make it work.
You need to add some validation to it based on your needs.
Please see it and let me know if it works or not.
Thank you.
https://codesandbox.io/s/funny-shadow-c0h7yi?file=/src/App.js

**Comment by shahabyazdi** [comment]
It seems to be a bug in the datepicker itself! tomorrow I will edit the example in the way to solve your issue temporarily and let you know about it

**Comment by shahabyazdi** [comment]
I upgraded the version of the datepicker to the latest release in the above example, and now it appears that the problem has been resolved.
