### ISSUE TITLE
How to close Calendar when using Tab key

### ISSUE THREAD

**Issue by Sarvenaz-s** [shahabyazdi/react-multi-date-picker#188]
Hi , I Use Several Date Picker and I use tab key to go to the next ones. When I use Tab I need my previous calendar to close, but it stays open.
I would appreciate it if you can help me. 
thanks

**Comment by Sarvenaz-s** [comment]
Hi
Thank you. Yes something like that, 
but I have multiple Date picker one after another. 
should I do this for every one of them?
is there any simpler solution?

**Comment by shahabyazdi** [comment]
Hi
You need to close the previous calendar when the input is blurred.
