### ISSUE TITLE
RunKit Issue

### ISSUE THREAD

**Issue by davidchoy** [shahabyazdi/react-multi-date-picker#19]
I'm trying to use [RunKit](https://npm.runkit.com/) to demonstrate a problem with the the DatePicker (it has to do with using the datepanel in mobile mode with a mininum selection date). RunKit, however, returns the error...

```
message: "Unexpected identifier"
SyntaxError Prototype
```

...for the default demo code at [https://npm.runkit.com/react-multi-date-picker](url) (linked to from [the react-mult-date-picker npm page](https://www.npmjs.com/package/react-multi-date-picker)):

```
require("react/package.json"); // react is a peer dependency. 

require("react-dom/package.json"); // react-dom is a peer dependency. 
var reactMultiDatePicker = require("react-multi-date-picker")
```

Any idea why?

**Comment by shahabyazdi** [comment]
Most likely the reason is that I built it as a ECMAScript module (esm) and runkit tries to require it as commonjs (cjs).

**Comment by davidchoy** [comment]
Yup; looks that way to me! Thanks. And Runkit currently does not support import.
I'll try to reproduce the problem elsewhere and create a new issue if I don't figure it out. (Mobile mode is not letting the date panel update when a min date is specified...)

**Comment by shahabyazdi** [comment]
I will definitely review the problem you mentioned tomorrow.

**Comment by davidchoy** [comment]
Cool, thanks; I created a [new issue](https://github.com/shahabyazdi/react-multi-date-picker/issues/20) for it.

https://github.com/shahabyazdi/react-multi-date-picker/issues/20

**Comment by davidchoy** [comment]
Thanks for the update here!

**Comment by shahabyazdi** [comment]
You're welcome 🙂
