### ISSUE TITLE
question: is it possbile to show 2 years in calendar in Datepicker(onlyMonthPicker)

### ISSUE THREAD

**Issue by Dulguun578** [shahabyazdi/react-multi-date-picker#190]
I need to show 2 years in calendar when I click Datepicker (onlyMonthPick) like when you use DatePicker like below. 
`<DatePicker
range
numberOfMonths=2
/>`

For onlyMonthPicker can I do something like this
`<DatePicker
range
onlyMonthPicker
numberOfYears=2
/>`

**Comment by shahabyazdi** [comment]
Not possible right now.
Will try to add this in the next versions.

**Comment by Dulguun578** [comment]
do you think its possible to write plugin for additional year
 `<DatePicker range onlyMonthPicker/>`

**Comment by shahabyazdi** [comment]
I'm working on it.

**Comment by shahabyazdi** [comment]
I upgraded the version of the datepicker to the latest release in the above example, and now it appears that the problem has been resolved.
