### ISSUE TITLE
change range hover background color

### ISSUE THREAD

**Issue by At1X** [shahabyazdi/react-multi-date-picker#191]
Is it possible to change the hover color in range mode? (default color is blue)
I had read the docs but nothing was found.
![Color](https://user-images.githubusercontent.com/51531010/235251508-c2fac03c-0c6a-43bb-ac10-44e2504e3a34.png)

**Comment by shahabyazdi** [comment]
Yes, you can do it with CSS, Here is an example:
https://codesandbox.io/s/datepicker-range-hover-color-f47fe7
There is also an example in the documentation that provides a CSS file that you can use:
https://shahabyazdi.github.io/react-multi-date-picker/colors/#red
