### ISSUE TITLE
question: Manually set Year and Month in datepicker

### ISSUE THREAD

**Issue by Dulguun578** [shahabyazdi/react-multi-date-picker#193]
In documentation you set year and month manually in calendar. (https://shahabyazdi.github.io/react-multi-date-picker/ref/).
How do I manually set year and month in datepicker without calendar disappearing?

**Comment by shahabyazdi** [comment]
There is an example in #185 that might work for you.
https://codesandbox.io/s/quiet-sea-vu8o03?file=/src/App.js:0-517

**Comment by Dulguun578** [comment]
thanks , that helps a lot

**Comment by shahabyazdi** [comment]
You're welcome
