### ISSUE TITLE
How do i access the selected date after onchange

### ISSUE THREAD

**Issue by osla-dev** [shahabyazdi/react-multi-date-picker#195]
I have been trying to access the value but i get a gaint object which contains the date in piece

**Comment by shahabyazdi** [comment]
Yes! that object is [DateObject](https://shahabyazdi.github.io/react-multi-date-picker/date-object/), and you can access to the javascript date using the [todate()](https://shahabyazdi.github.io/react-multi-date-picker/events/#onchange-(single-mode)) method.

```js
dateObject.toDate()
```

**Comment by osla-dev** [comment]
This was really helpful thanks a lot

**Comment by shahabyazdi** [comment]
You're welcome
