### ISSUE TITLE
Props transfered to DOM element

### ISSUE THREAD

**Issue by Silac** [shahabyazdi/react-multi-date-picker#199]
Hi there, just found out about your datepicker, really nice work.

I've got a small issue though, it seems that multiple props end up on the div containing the picker at the end and React throws an error for each of them.

Here are 2 props I found that throw an error:
- portal
![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/3785801/94e8eef3-7ef9-4924-b0d1-cfbe5119100c)
- offsetY
![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/3785801/2c4ae100-c6a0-430c-a75a-1bbebf3af6b8)

Obviously there could be more

**Comment by shahabyazdi** [comment]
Please upgrade to v4.1.1, this will fix the problem.
Thank you.
