### ISSUE TITLE
Typescript error:- The type of dateSeparator=" - "  is boolean. 

### ISSUE THREAD

**Issue by naveenambookken** [shahabyazdi/react-multi-date-picker#200]
![image](https://github.com/shahabyazdi/react-multi-date-picker/assets/65295713/aac46be8-e08f-468f-b862-5775b1939b99)

**Comment by arnurkuatov** [comment]
Did you resolve this problem?

**Comment by shahabyazdi** [comment]
Yes, it's fixed in version 4.1.1
