### ISSUE TITLE
Question: About changing the minute interval of the TimePicker

### ISSUE THREAD

**Issue by tatsuya-develop** [shahabyazdi/react-multi-date-picker#201]
Hi, thanks for the great library.

I have a question about TimePicker.

When selecting minutes, I assume the value changes by 1. Is it possible to change this by 15 minute increments or even 30 minute increments?

I am currently developing a schedule adjustment app and would like the values to change in 15 or 30 minute increments, like Google Calendar, rather than minute-by-minute changes.

If others have a need for this, please consider developing it.

**Comment by tatsuya-develop** [comment]
The ability to advance time in 15-minute and 30-minute increments is no longer necessary.

Therefore, this Issue and Pull Request are closed.

**Comment by shahabyazdi** [comment]
The documentation is here (for later use)

https://shahabyazdi.github.io/react-multi-date-picker/plugins/time-picker/#utilizing-step-for-arrow-icons

**Comment by tatsuya-develop** [comment]
@shahabyazdi 

Oh!It was already there.

Excuse me, I could't find it.

Thanks for the reply!
