### ISSUE TITLE
Mobile selected date style issue

### ISSUE THREAD

**Issue by emileindik** [shahabyazdi/react-multi-date-picker#202]
Using "rmdp-mobile" class in the multi date DatePicker causes a selected date to appear as a hovered date on mobile.
![IMG_46E52BEA1225-1](https://github.com/shahabyazdi/react-multi-date-picker/assets/8562758/6c50585a-c81c-4a91-b42b-2026803b077d)
In this image, I selected "31" but it doesn't show as dark blue. It shows as light blue as if I hovered over it.

Thanks for this great library!

**Comment by emileindik** [comment]
Can be combined with this reported issue #161

**Comment by shahabyazdi** [comment]
Sorry for the late response.
I will work on it.

**Comment by emileindik** [comment]
Let me know if there is anything I can do to help!

**Comment by shahabyazdi** [comment]
Please try v4.3.6 and let me know if it doesn't fix.

**Comment by emileindik** [comment]
Yes the select date issue has been solved, thank you!
However, when unselecting a date, it still remains with the "hovered" color styling until the user clicks somewhere else.

**Comment by shahabyazdi** [comment]
It should be fixed in v4.4.1.

**Comment by emileindik** [comment]
Fixed! Thank you
