### ISSUE TITLE
React does not recognize the X prop on a DOM element

### ISSUE THREAD

**Issue by mssoheil** [shahabyazdi/react-multi-date-picker#208]
There are some warning regarding the passing props to the DOM for e.g. handleValueChange, openCalendar these are passed to the dome and since they are not valid DOM attribute the browser gives a warning and since they are the library internals even if you don't pass them you get the warning

**Comment by AlekseyMalakhov** [comment]
I had the same issue - updating to 4.1.2 helped me

**Comment by mssoheil** [comment]
updated to the v4.1.2 and it has the same problem

**Comment by nst2pl5** [comment]
I downgraded 4.1.2 to version 4.1.1, but that didn't fix the warning either.

**Comment by shahabyazdi** [comment]
@mssoheil , @nst2pl5 
I double-checked the code and did some tests, but there is no such warning in the console at least in v4.1.1 and later. are you sure you completely uninstalled the previous version in the node_module (npm uninstall react-multi-date-picker) and installed it again?

**Comment by hamidyfine** [comment]
This error is still there in version 4.5.0. Any update or solution on this? I downgrade to 4.1.1 and still got error.

**Comment by shahabyazdi** [comment]
@hamidyfine can you send the log here?

**Comment by hamidyfine** [comment]
```
React does not recognize the `openCalendar` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `opencalendar` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

```
React does not recognize the `handleValueChange` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `handlevaluechange` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by MR-Mostafa** [comment]
I had the same issue - v 4.5.2

**Comment by Shaker-Hamdi** [comment]
I still have the exact same problem, I'm on version "4.4.1".
Any updates on this?
