### ISSUE TITLE
Hide calendar on blur

### ISSUE THREAD

**Issue by zahraMohammaddoust** [shahabyazdi/react-multi-date-picker#211]
تقویم تو blur بسته نمیشه و در موبایل مشکل ساز شده

**Comment by shahabyazdi** [comment]
سلام
امکانش هست نمونه کدتون که مشکل ساز شده رو اینجا بفرستید تا بتونم دیباگ کنم ؟

**Comment by zahraMohammaddoust** [comment]
مشکلم با closeCalendar حل شد. ممنون از شما
inputRefs[0].current.closeCalendar();

**Comment by shahabyazdi** [comment]
خواهش میکنم

**Comment by shahabyazdi** [comment]
با این تیکه کد نمیتونم متوجه شم ایراد از کجاست.
الان برام سوال پیش اومده که چرا ref شما یک آرایه است.
سوال بعدی که برام پیش اومده اینه که خود دیت پیکر handleClickOutside داره و چرا روی پروژه شما کار نمیکنه.
اگر امکان داره کد کامل رو بدید تا بتونم دیباگ کنم.
مرسی

**Comment by zahraMohammaddoust** [comment]
در مورد ارایه بودن ref میتونه ارایه هم نباشه و من صرفا چون چندین تکست فیلد دارم که براشون ref باید تعریف میشد همرو توی یه ارایه ریختم.
handleClickOutside دقیقا چه کاری انجام میده؟
تا قسمتی که مربوط به موضوع هست و میتونم بفرستم کد کامل حجمش زیاده

const inputRefs = [
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
  useRef(null),
];
return (
  <div
    className="date TextField"
  >
    <label
      id="damageDatelabel"
      className={
        damageDateInputFocused || damageDate
          ? "focused"
          : "label"
      }
      style={
        damageDateInputFocused
          ? { color: "#1976d2" }
          : { color: "rgb(125 125 125)" }
      }
    >
      تاریخ هزینه
    </label>
    <span
      className="datepicker-wrapper"
      onFocus={() => {
        setDamageDateInputFocused(true);
      }}
      onBlur={(event) => {
        try {
          setDamageDateInputFocused(false);
            inputRefs[7].current.closeCalendar();
        }
        catch (e) {
          window.alert(e.message);
        }
      }}
    >
      <DatePicker
        calendar={persian}
        locale={persian_fa}
        calendarPosition="bottom-right"
        onChange={getDate}
        value={damageDate}
        id="damageDate"
        type="tel"
        ref={inputRefs[7]}
      />
    </span>
  </div>
)

**Comment by zahraMohammaddoust** [comment]
راه حلی نداره؟
