### ISSUE TITLE
current date is automatically set on open for first time

### ISSUE THREAD

**Issue by aliqb** [shahabyazdi/react-multi-date-picker#213]
when there is no defualt date and we open datepicker for the first time, current date set automatically and onchage is called, I am using date state with a useEffect hook and this cause extra call at first.
is there anyway to disable auto setting

**Comment by shahabyazdi** [comment]
Yes.
You can set `onOpenPickNewDate` prop to `false`.

**Comment by aliqb** [comment]
thanks
