### ISSUE TITLE
Multiple Datepicker closing after once selecting a date

### ISSUE THREAD

**Issue by mtochi** [shahabyazdi/react-multi-date-picker#215]
Multiple Datepicker closing after once selecting a date, it won't let me select more dates in one go, for each date that I want to select I need to open the date picker, and then choose one date and then it will close, and I would need to repeat this process for as many dates I want to choose...

**Comment by shahabyazdi** [comment]
I tested the issue you reported with the multiple-mode functionality, but I was unable to reproduce the problem on my end. The multiple mode seems to be working properly in this example [here](https://shahabyazdi.github.io/react-multi-date-picker/multiple/#multiple-mode).

Could you please provide a minimal CodeSandbox example that demonstrates the bug you are seeing? That would really help me better understand the issue and debug what could be going wrong. I'd be happy to take a look and see if I can spot the cause.
