### ISSUE TITLE
Refresh page on Time Picker

### ISSUE THREAD

**Issue by mauro-rogledi** [shahabyazdi/react-multi-date-picker#223]
If I use the time picker, the UI does not refresh values.

Try on this app.

https://stackblitz.com/edit/stackblitz-starters-nwtped?file=src%2FApp.tsx

If you change value by UI time picker of from control , the tick values displayed do not changes. Change only the value into from control.
If you uncomment the setTxt in the onchange(), the values o tick changed, but not in To field.

If you modify time by keyboard by text, the values change correctly

**Comment by shahabyazdi** [comment]
fixed in v4.3.2

**Comment by mauro-rogledi** [comment]
Works.
Thanks !!!!
