### ISSUE TITLE
when a day is disabled, it is possible to entering that day in the input..

### ISSUE THREAD

**Issue by BasetMamshpoor** [shahabyazdi/react-multi-date-picker#230]
If a day is disabled, by entering that day in the input, it is easy to choose the disabled day or even disable the edit, by decrease the hour, you can go to the previous days (even if it is disabled).
how can i fix this bug?
![Screenshot 2023-10-06 131110](https://github.com/shahabyazdi/react-multi-date-picker/assets/112559243/9393ccf6-c817-4abd-b1e1-1ac63483a782)

**Comment by shahabyazdi** [comment]
Thank you for reporting this bug, it will be fixed in v4.3.4.

**Comment by shahabyazdi** [comment]
Sorry, I forgot to fix the timer picker bug. You need to install v4.3.5 to have the time picker bug fix too.

**Comment by BasetMamshpoor** [comment]
thinks, it works
