### ISSUE TITLE
Prevent closing on change event in single mode

### ISSUE THREAD

**Issue by nazaninroozbahani** [shahabyazdi/react-multi-date-picker#231]
How to prevent closing on change event in single mode?
I saw the onClose event, but I don't want to disable onBlur and custom close buttons, just want to prevent on change date .

**Comment by shahabyazdi** [comment]
Please follow this example:
https://codesandbox.io/s/prevent-closing-the-calendar-9kw89r

**Comment by nazaninroozbahani** [comment]
Hi, this solution is working, but it just prevent closing calendar on each select, but the onFocusedDateChange is calling onClose. Actually now we have onClose just without closing calendar.

**Comment by nazaninroozbahani** [comment]
This solution not working in portal mode.
