### ISSUE TITLE
Property 'closeCalendar' does not exist on type 'HTMLDivElement'.

### ISSUE THREAD

**Issue by nazaninroozbahani** [shahabyazdi/react-multi-date-picker#232]
Hi.
according to docs:
https://shahabyazdi.github.io/react-multi-date-picker/fa/typescript/
we should consider ref type as HTMLDivElement.
but when we want to trigger close or open manually: get this error in typescript:
datePickerRef.current.closeCalendar(); 
get this error in typescript:
Property 'closeCalendar' does not exist on type 'HTMLDivElement'.ts(2339)

**Comment by shahabyazdi** [comment]
Thank you for reporting this bug, it will be fixed in the next release.
