### ISSUE TITLE
weekDays, months type problem

### ISSUE THREAD

**Issue by Nippondanso** [shahabyazdi/react-multi-date-picker#24]
- how it is **now** in your code:

index.d.ts => weekDays?: [string[]], 
                          months?: [string[]],
![image](https://user-images.githubusercontent.com/28148918/111483483-7cb62a00-873d-11eb-9219-a0e392ca76d8.png)
![image](https://user-images.githubusercontent.com/28148918/111483545-893a8280-873d-11eb-87e9-9f4eccb6ca07.png)
![image](https://user-images.githubusercontent.com/28148918/111483693-b38c4000-873d-11eb-99ff-321239872b58.png)

and if if chose code like this project will build, but in calendar i will not see my data:  
![image](https://user-images.githubusercontent.com/28148918/111483817-d4549580-873d-11eb-97d7-80daf48f2157.png)
![image](https://user-images.githubusercontent.com/28148918/111483851-ddddfd80-873d-11eb-9631-27a75b3af4a5.png)
![image](https://user-images.githubusercontent.com/28148918/111484028-0b2aab80-873e-11eb-8603-b91734c4728b.png)

- how it work in my case if **i change** it:

index.d.ts => weekDays?: string[], 
                      months?: string[],    
![1](https://user-images.githubusercontent.com/28148918/111483119-2e089000-873d-11eb-80b2-2253450fedb0.png)
![2](https://user-images.githubusercontent.com/28148918/111483121-2ea12680-873d-11eb-8df9-baa830977d42.png)
![3](https://user-images.githubusercontent.com/28148918/111483122-2f39bd00-873d-11eb-8fe6-e18c9b51b4a2.png)

**Comment by shahabyazdi** [comment]
Yes you are right.
I need to change the types to string[] | [string[]]

**Comment by Nippondanso** [comment]
thank you for your datepicker/calendar - it is very functional and comfortable

**Comment by shahabyazdi** [comment]
> thank you for your datepicker/calendar - it is very functional and comfortable

You're welcome

I'm working on it...

**Comment by shahabyazdi** [comment]
It fixed in version 2.2.7.

**Comment by shahabyazdi** [comment]
I'm not sure if you see this comment or not!
But I noticed that you are passing date as initial value without saving it in the state.
This action causes all selected dates to be lost in the next render.
Because in the next render, the date is passed as the value, considered as initial value.
That's why it's best to keep the dates in a state like this:

```javascript
const [value, setValue] = useState([moment().format('YYYY-MM-DD')])
.
.
.
<DatePicker
   value={value}
   onChange={setValue}
   multiple
/>
```

**Comment by Nippondanso** [comment]
Thank you! this is very useful advice!
