### ISSUE TITLE
multiple = {false} not working

### ISSUE THREAD

**Issue by sharan98727** [shahabyazdi/react-multi-date-picker#25]
const FormMultipleDatePicker: FunctionComponent<TimeSelectorHookProps> = ({
                                                                      displayName, name, placeholder, menuPortalTarget, minDate, maxDate,
                                                                      className="", asterisk = true, variant="", isEdit, isMultiDatePickerDisabled = false,
                                                                      placeHolderText = ""
                                                                  }) => {
    const {errors, control} = useFormContext();
    // @ts-ignore
    return <FlexColumn className={className + " px-2 mb-3"}>
        <LabelHeading variant={variant}>{displayName}{asterisk?<span className="text-danger"> * </span>:''}</LabelHeading>
        <EntryDate>
        <Controller
            control={control}
            name={name}
            placeholder={placeholder}
            menuPortalTarget={menuPortalTarget}
            render={({onChange, value}) => (
                isEdit ?
                <DatePicker
                    value={value}
                    onChange={onChange}
                    minDate={minDate}
                    maxDate={maxDate}
                    type= "input"
                /> :
                <DatePicker
                    multiple
                    value={value}
                    onChange={onChange}
                    minDate={minDate}
                    maxDate={maxDate}
                    type= "input"
                    disabled = {isMultiDatePickerDisabled}
                    placeholder = {placeHolderText}
                    onlyShowInRangeDates
                />
            )}
        />
        </EntryDate>
        <ErrorText>{errors[name] && errors[name].message}</ErrorText>
    </FlexColumn>
};

in this code if i put multiple={false} the date picker is still allowing user to select multiple dates. is this a bug in the library itself. iam using datepicker with react-hookforms and controller

**Comment by shahabyazdi** [comment]
What value do you enter to DatePicker as initial value? If type of initial value is array, even if you set multiple to false., The DatePicker considers multiple to true.

**Comment by shahabyazdi** [comment]
I'm going to close this issue .
If you still have any problem related to this issue please reopen it.
