### ISSUE TITLE
چگونه فقط تاریخ و روز های مشخصی را قابل انتخاب کنیم؟

### ISSUE THREAD

**Issue by RezaBakhshiNia** [shahabyazdi/react-multi-date-picker#259]
سلام و عرض ادب.
آیا می توان آرایه ای تاریخ و روز های مشخصی به کامپوننت داد که فقط آنها قابل انتخاب باشند؟
فرض کنید پزشکی در هر ماه روز های مشخصی را ویزیت دریافت می کند.

**Comment by Rezaraki** [comment]
سلام 
میشه ولی یکم کار داره وباید از طریق mapDays انجامش بدی. اینطوری که روی روزها map میزنه و هر روزی که داخل اون آرایه هست باید داخل آبجکتی که برمیگردونی   disabled: true باشه
`<DatePicker
  mapDays={({ date }) => {
    let isWeekend = [0, 6].includes(date.weekDay.index)
    
    if (isWeekend) return {
      disabled: true,
      style: { color: "#ccc" },
      onClick: () => alert("weekends are disabled")
    }
  }}
/>`
https://shahabyazdi.github.io/react-multi-date-picker/map-days/

**Comment by RezaBakhshiNia** [comment]
سلام و وقت بخیر، با تشکر از دوست عزیزی که راهنمایی کردن، راه حل انجام دادنش به این شکل هست:

`<DatePicker
  onOpenPickNewDate={false}
  format="YYYY/MM/DD"
  calendar={persian}
  locale={persian_fa}
  mapDays={({ date }) => {
    const dates = ['2024-01-03', '2024-01-08', '2023-12-27',];
    const currentDate = new Date(date.unix * 1000).toISOString().split('T')[0];
    if (dates.includes(currentDate)) {
      return {
        disabled: false,
        style: { color: "inherit" },
        onClick: () => alert("This date is enabled")
      };
    } else {
        return {
          disabled: true,
          style: { color: "#d3d3d3" },
          onClick: () => alert("This date is disabled")
        };
      }
  }}
/>`
