### ISSUE TITLE
Children prop type is not defined for DatePicker and Calendar 

### ISSUE THREAD

**Issue by andrii-kifiak-deepsee** [shahabyazdi/react-multi-date-picker#26]
Hello I have noticed that in demo page we are able to insert children elements inside of `DatePicker` and `Calendar` elements but seems like the type for children is not defined.
Therefore I am getting such error:
`Type '{ children: string; multiple: true; plugins: Element[]; onChange: (v: any) => void; }' is not assignable to type 'IntrinsicAttributes & CalendarProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & CalendarProps'. `
  
  I can do PR for this if so...
  Thanks

**Comment by shahabyazdi** [comment]
Hello
Thanks for reminding this point , I added the React.ReactNode for the children prop.
Please tell me if there is anything else regarding this issue.

**Comment by andrii-kifiak-deepsee** [comment]
@shahabyazdi  Hello, thank you for the quick reaction.
Shouldn`t it be added in the same way to `DatePicker` instance as well?

**Comment by shahabyazdi** [comment]
Your welcome.
I don't think so, because DatePicker accepts every Calendar props including its own props.
```javascript
export default function DatePicker(props: CalendarProps & DatePickerProps): React.ReactElement
```
