### ISSUE TITLE
Use Range and MultiPicker with onlyMonth option

### ISSUE THREAD

**Issue by lharby** [shahabyazdi/react-multi-date-picker#27]
Hello

I just started using this picker today, and it is fantastic. I was just wondering if it is possible to create range options for months as well as multi picker for months also. 

So I guess you could have 

`12/2020 - 03/2021` for range

`09/2020, 10/2020, 02/2021` for multi picker select

I have made various iterations in our storybook but it seemed like multi and range was only an option for the day calendar. 

Hope this is possible.

**Comment by shahabyazdi** [comment]
Hi
Thanks for choosing this datepicker.
As you said the multiple and range options only work in day calendar.
But I'll try to add the range & multiple mode for `only month` and `only year` pickers as well in the next few days...

**Comment by shahabyazdi** [comment]
I have not released version 2.3.0 yet and will probably release it later today or tomorrow. 
But I updated the demo page and added the features you wanted.
Please see them and let me know if the changes I have made do not match the features you want.

1. [Multiple Month Picker](https://shahabyazdi.github.io/react-multi-date-picker/multiple/#multiple-month-picker)
2. [Multiple Year Picker](https://shahabyazdi.github.io/react-multi-date-picker/multiple/#multiple-year-picker)
3. [Range Month Picker](https://shahabyazdi.github.io/react-multi-date-picker/range/#range-month-picker)
4. [Range Year Picker](https://shahabyazdi.github.io/react-multi-date-picker/range/#range-year-picker)

**Comment by lharby** [comment]
This looks amazing, thank you so much. Really great work.

**Comment by shahabyazdi** [comment]
You're welcome.
I will release the nex version as soon as I can.

**Comment by shahabyazdi** [comment]
The package is upgraded to the latest version .
Please reopen this issue if you have any problem.
Thank you.
