### ISSUE TITLE
Add events onKeyUp, onPressEnter

### ISSUE THREAD

**Issue by AliOstadhoseinKharat** [shahabyazdi/react-multi-date-picker#276]
Thank you for your good library.
Does this library have onPressEvent or onKeyUp events ?

**Comment by shahabyazdi** [comment]
Hi,
You can use a [custom input ](https://shahabyazdi.github.io/react-multi-date-picker/types/#custom-(input))and pass your desired methods to it.

**Comment by AliOstadhoseinKharat** [comment]
Thanks 👍🏻
