### ISSUE TITLE
How to open/close date picker by click on button outside?

### ISSUE THREAD

**Issue by Amiini** [shahabyazdi/react-multi-date-picker#28]
Hi
Is it possible to open/close date picker by click on button outside of it? is there any method?
thank u

**Comment by shahabyazdi** [comment]
Hi
Yes , here is an example of it:

https://shahabyazdi.github.io/react-multi-date-picker/#forward-ref

**Comment by Amiini** [comment]
Thank you

**Comment by shahabyazdi** [comment]
You're welcome.
