### ISSUE TITLE
arrow={false} is not working

### ISSUE THREAD

**Issue by PavithraSutantraa** [shahabyazdi/react-multi-date-picker#30]
arrow={false} doesn't disable arrow.. Even in the example provided here it's  not working
https://shahabyazdi.github.io/react-multi-date-picker/arrow/

**Comment by shahabyazdi** [comment]
it works !

![Screenshot from 2021-04-10 14-07-57](https://user-images.githubusercontent.com/18695593/114265543-9548f580-9a06-11eb-9c44-2e239e9d8d7f.png)
![Screenshot from 2021-04-10 14-08-06](https://user-images.githubusercontent.com/18695593/114265545-98dc7c80-9a06-11eb-9b5c-8fc710cc469d.png)

**Comment by PavithraSutantraa** [comment]
Arrow Property is for the arrow on the left and right to navigate the right?

**Comment by shahabyazdi** [comment]
The arrow element between the calendar & input !
If you want to customize the previous and next buttons, I will add that possibility in the next version.

**Comment by PavithraSutantraa** [comment]
I misunderstood it as the arrow to navigate. 

I am using DatePicker in my react app to mark multiple holidays at once for a chosen month. If the user choose Feb, he can choose dates between 02/01/2021 and 02/28/2021. For this I have used minDate and maxDate. When user clicks on a button, DatePicker opens in a Modal and it opens to current month and the arrows to navigate are disable because of the min and max dates. User can navigate to Feb clicking on the month but inactivity of arrows is a little confusing. So I was hoping to not show the navigation arrows to avoid confusion. 

Anyways, datePicker has been a lifesaver. Thank you. It will be amazing if you add this feature in the next version

**Comment by shahabyazdi** [comment]
I will add it tommorow.

**Comment by shahabyazdi** [comment]
Disabling and customizing the navigation buttons added in version 2.5.0.
Demo : https://shahabyazdi.github.io/react-multi-date-picker/buttons/
