### ISSUE TITLE
How to force the calendar to show a particular month instead of the current month

### ISSUE THREAD

**Issue by PavithraSutantraa** [shahabyazdi/react-multi-date-picker#31]
I am using multiple option and I want to force the calendar to open to a particular month. How to do it? 

Thanks in advance.

**Comment by shahabyazdi** [comment]
Use the currentDate prop.

```javascript 
import {DateObject} from "react-multi-date-picker" 
.
.
.
return (
   <DatePicker currentDate={new DateObject ({ year:2021,month:4,day:12})}
)
```

**Comment by shahabyazdi** [comment]
I put an example on the [demo page](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#opening-calendar-on-the-specified-date) to define a specific date to open the calendar.

**Comment by shahabyazdi** [comment]
In version 2.5.1, There is another way by which you can change the year and month in the calendar, which you can see the example here:
1- [Manually Set Year And Month In Calendar](https://shahabyazdi.github.io/react-multi-date-picker/ref/#manually-set-year-and-month-in-calendar)
2- [Manually Set Year And Month In DatePicker](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#manually-set-year-and-month-in-datepicker)
