### ISSUE TITLE
can i set month throw props?

### ISSUE THREAD

**Issue by Nippondanso** [shahabyazdi/react-multi-date-picker#32]
i need calculate month than set month from props.
is it real?

**Comment by shahabyazdi** [comment]
If you want to manually set the month to datepicker you can use currentDate prop.
Please [click here](https://codesandbox.io/s/custom-month-8szev?file=/src/App.js) to see the example from the codesandbox.

Or [click here](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#opening-calendar-on-the-specified-date) to see another example from the demo page.

Please let me know if you had any problem related to this issue.

**Comment by shahabyazdi** [comment]
In version 2.5.1, There is another way by which you can change the year and month in the calendar, which you can see the example here:
1- [Manually Set Year And Month In Calendar](https://shahabyazdi.github.io/react-multi-date-picker/ref/#manually-set-year-and-month-in-calendar)
2- [Manually Set Year And Month In DatePicker](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#manually-set-year-and-month-in-datepicker)

**Comment by Nippondanso** [comment]
Hello, thank for an answer.
The first method is not suitable because it has effect only on datepicker.

The second method doesnt work in some reason...
![image](https://user-images.githubusercontent.com/28148918/114877700-34575e00-9e08-11eb-85bc-9ad57a94e71a.png)
![image](https://user-images.githubusercontent.com/28148918/114877729-3caf9900-9e08-11eb-9f53-38070cb87d35.png)


(i updated the react-multi-date-picker to final version)
![image](https://user-images.githubusercontent.com/28148918/114877774-46d19780-9e08-11eb-801c-4950f7ff2b1f.png)

**Comment by shahabyazdi** [comment]
I need to move the ref type from the datepicker to the calendar prop.
I will fix it now ...

**Comment by Nippondanso** [comment]
i have no idea why, but it still not work for me  :C

![image](https://user-images.githubusercontent.com/28148918/114884348-5fdd4700-9e0e-11eb-9819-731fedcd4042.png)

**Comment by shahabyazdi** [comment]
Please give me some time to work on it...

**Comment by shahabyazdi** [comment]
I found a temporary solution for this problem.
Set 'any' to useRef.

```javascript 
const ref = useRef<any>()
```
![Screenshot from 2021-04-15 19-28-30](https://user-images.githubusercontent.com/18695593/114891290-00d4fd80-9e21-11eb-8b2a-9c3035b22c09.png)

**Comment by shahabyazdi** [comment]
You can also use // @ts-ignore 

```javascript
<div className="App">
   <Calendar
     // @ts-ignore
     ref={ref}
   />

   <button
     onClick={() => {
       // @ts-ignore
      ref.current.set(
         "month",
         // @ts-ignore
         ref.current.date.month.number + 1
       )
     }}
   >
     +
   </button>
</div>
```

**Comment by Nippondanso** [comment]
hello, sorry for delay.
unfortunately, none of the ways worked for me

First method has no effect and prop  in <Calendar/> throw error like on the screens above.
Second method crushed all progect :0

so i found workaround:
i chacked current month -> that save it in state -> than calculate abs between current month and target month -> programmely click on right side of arrows in calendar :D
