### ISSUE TITLE
Calendar Style

### ISSUE THREAD

**Issue by jabdon00** [shahabyazdi/react-multi-date-picker#322]
is there any way to see calendar like this picture ? (from outlook)
![image](https://github.com/user-attachments/assets/1f7ac569-f179-4125-bc0e-1d6f18add847)

**Comment by dadang-hawari** [comment]
![Screenshot 2024-10-25 101525](https://github.com/user-attachments/assets/d534ef3a-897b-4653-95f0-113b73fa1fa8)
yeah you can by override the default style. But you must know how to override the style, and it might be a little challenging
