### ISSUE TITLE
Disabled chevrons for minDate and maxDate can be activated after selecting a date

### ISSUE THREAD

**Issue by lharby** [shahabyazdi/react-multi-date-picker#33]
I'm using a month multi selector (although it seems to be affecting other iterations of the date picker). 

To replicate. Set a min and maxDate. Select one of the months within the two dates, it enables the forward and back arrows and allows navigation to other dates which should otherwise be disabled. 

I've uploaded some screenshots here: https://imgur.com/a/73FZv19

**Comment by shahabyazdi** [comment]
Hi
Thank you for reporting this bug.
The problem you mentioned seems to be fixed in v2.5.4.
Please install it and let me know if it doesn't work.

**Comment by lharby** [comment]
Thank you! I am off for a few days but I will check it out later next week and update. I really appreciate it.

**Comment by shahabyazdi** [comment]
You're welcome.
It's Ok.

**Comment by shahabyazdi** [comment]
I'm going to close this issue.
Please reopen this if the problem persists.
