### ISSUE TITLE
Date panel not working in typescript

### ISSUE THREAD

**Issue by venkat-sitpl** [shahabyazdi/react-multi-date-picker#34]
Hi,

React multi date picker , I'm using in typescript but that is getting error like this 
![image](https://user-images.githubusercontent.com/67685686/115020448-3c7ece80-9ed8-11eb-96e7-848cd7eee19b.png)

and React multi date picker for typescript not available in NPM repo

**Comment by shahabyazdi** [comment]
Hi
I added the definition types of all plugins and published the package.

``` import { DatePanel } from "react-multi-date-picker/plugins"``` is deprecated.

please install v2.5.4 and use ``` import DatePanel from "react-multi-date-picker/plugins/date_panel"```
