### ISSUE TITLE
MinDate is not working with DatePanel plugin

### ISSUE THREAD

**Issue by AyushRawat1996** [shahabyazdi/react-multi-date-picker#36]
I want to disable previous dates in the calendar so I am using **minDate** prop.
![image](https://user-images.githubusercontent.com/29222583/115379733-6d6c4580-a1ef-11eb-89dc-0df335e9db21.png)

Then I'm getting error - 

![image](https://user-images.githubusercontent.com/29222583/115379523-3bf37a00-a1ef-11eb-9750-b098ae0cff6b.png)

But when I remove **minDate** prop, while using DatePanel plugin, everything works fine

**Comment by shahabyazdi** [comment]
Hi,
Thank you for mentioning this bug.
It seems to be fixed in v2.5.5

**Comment by AyushRawat1996** [comment]
Thanks @shahabyazdi for the quick response.
Now it is working absolutely fine.

**Comment by shahabyazdi** [comment]
You're welcome.
