### ISSUE TITLE
Missing translatable labels in plugins

### ISSUE THREAD

**Issue by Moinax** [shahabyazdi/react-multi-date-picker#37]
Hi, it would be really good if we could provide the translated labels to your plugins (e.g. the toolbar).
I saw that you started to handle this by taking the `locale` from the state, but it only works for the translations you implemented.
Instead I would foresee 3 `props` to provide the right label for each button, like you did for the `weeks` and `months` in the base library.

Anyway, really great job, I'm surprised your library is not used more than that (according to npmtrends).

**Comment by Moinax** [comment]
I saw that you already did a change for the `toolbar` plugin, I didn't expect you work on that so fast :+1: 

It would be great if you could do the same for the `dates panel` too (the "Dates" label).

Do you know when I can expect a new release ? I was about to duplicate your plugin to fix this locally, but if you do a release soon, I'll wait for it ;)

**Comment by shahabyazdi** [comment]
Hello,
Thanks for your comment, I really appreciate.
I added a prop for changing the default names of the toolbar, and [here's](https://shahabyazdi.github.io/react-multi-date-picker/plugins/toolbar/#custom-names) an example of it.
I hope to do the same for other plugins tomorrow.

**Comment by Moinax** [comment]
Thanks to you, yeah I saw it in your commit, but I believe you didn't create a release yet, so it's still not available.

**Comment by Moinax** [comment]
Ho my bad, there is no release on github, but I see the release on NPM :+1:

**Comment by shahabyazdi** [comment]
Do you also use the settings plugin? If you only need to change the DatePanel header , I will do it now ...

**Comment by Moinax** [comment]
Not at the moment, I only use the `Toolbar` and `DatePanel` in my project, which are exactly what our product owner wanted, so again :+1:

**Comment by shahabyazdi** [comment]
wait a moment ...

**Comment by shahabyazdi** [comment]
Please install v2.5.6 and use the header prop to change the DatePanel header.

https://shahabyazdi.github.io/react-multi-date-picker/plugins/panel/#custom-header-name

**Comment by Moinax** [comment]
Thanks a lot, it works like a charm :+1: 

I let you close the issue when everything is done on your side, but for me, it's perfect.

Thanks again for your work

**Comment by shahabyazdi** [comment]
ِِYour Welcome , I'm glad I could do something.
Thanks for the image you sent.
Please tell me if you have any other issues.
