### ISSUE TITLE
Typo mistake in the toolbar plugin

### ISSUE THREAD

**Issue by Moinax** [shahabyazdi/react-multi-date-picker#38]
I believe there is a mistake in typo, you wrote `formar` instead of `format`

https://github.com/shahabyazdi/react-multi-date-picker/blob/57123b6a007e4d092773da0aa45693459aa4c2c4/plugins/all/toolbar/toolbar.js#L47

**Comment by shahabyazdi** [comment]
I'm very sorry to answer you late, I was off yesterday.
It fixed in Branch Develop.
Thank you very much for this report.
-
Anyway I was looking for an opportunity to make some fundamental changes in the plugins section, I think I will dedicate the next few days to it.
