### ISSUE TITLE
How to reset the value from the calender

### ISSUE THREAD

**Issue by vivekkbaskaran** [shahabyazdi/react-multi-date-picker#4]
I want to reset the calendar value after submit. Please help me on this.

**Comment by shahabyazdi** [comment]
You need to store your value in state:
```javascript
const [value, setValue] =  useState(initialValue)
```
And set it to Calendar or DatePicker:
```javascript
<Calendar value={value} onChange={setValue} />
```
And in you're onSubmit method reset the value like this 
```javascript
setValue(initialValue)
```
Please feel free to email me whenever you have any questions , i'll be happy to help, and open an issue only when you think you're problem is a real DatePicker issue

**Comment by shahabyazdi** [comment]
Also I edited previous example by adding a reset button on it , so you can see how it works:

https://codesandbox.io/embed/input-calendar-jjkoh?file=/src/App.js&codemirror=1

**Comment by vivekkbaskaran** [comment]
Hey You are great Thank you so much :-)
