### ISSUE TITLE
readOnly <Calendar /> support

### ISSUE THREAD

**Issue by AshenCat** [shahabyazdi/react-multi-date-picker#40]
Thank you for this awesome calendar picker component!
I just have a question about the approach for making the calendar component read only and not change values when a date is clicked?

also, Typo on Calendar ref page (Opene instead of Open(?))
https://github.com/shahabyazdi/react-multi-date-picker/blob/00569f76349fef9c6bc87e9a7026e6ca3e326c8c/website/src/docs/ref.js#L50

**Comment by shahabyazdi** [comment]
Hello
Thank you very much for reminding the typo.

Is this enough to make the calendar readOnly?
```javascript
import { Calendar } from "react-multi-date-picker";
import { useState } from "react";

export default function App() {
  const [value, setValue] = useState();

  return <Calendar value={value} onChange={() => setValue({})} />;
}
```
Or do I need to add a readOnly prop for this purpose?

**Comment by AshenCat** [comment]
hmmm, I see that it works when the `value` is on a `useState`. For my use case, I have an array of objects with dates so I don't have a `setValue` for each iteration as all of the dates is on a single state. Putting an onChange with an empty function does not make the calendar read only.

**Comment by shahabyazdi** [comment]
I will add the `readOnly` prop in v2.9.0.
So that, when `readOnly` is activated, the user can no longer select a new date by the calendar

**Comment by shahabyazdi** [comment]
`readOnly` and `disabled` added to version 2.9.0.
Adding these properties disables the calendar and prevents the user from `selecting` or `editing` the initial value.
Please take a look at these links and let me know if the problem persists.

1- [Read Only Calendar](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#read-only-calendar)
2- [Disabled Calendar](https://shahabyazdi.github.io/react-multi-date-picker/other-examples/#disabled-calendar)

**Comment by AshenCat** [comment]
works perfectly now, thank you!

**Comment by shahabyazdi** [comment]
You're welcome.
