### ISSUE TITLE
How to get the value of multiple date picker with custom input component?

### ISSUE THREAD

**Issue by jessduran** [shahabyazdi/react-multi-date-picker#41]
Hello, is there a way to set the state from the value of the multiple date picker with a custom component? 

I have this in my form component:
```
const [dates, setDates] = React.useState([]);

<DatePicker
  multiple
  plugins={[
    <DatePanel />
  ]}
  type="custom"
  render={<DateInput />}
  onChange={setDate}
  value={date}
/>
 ```

```
const DateInput = ({ openCalendar, stringDates, handleValueChange }) => (
  <TextField
    onFocus={openCalendar}
    value={stringDates.join(', ')}
    onChange={handleValueChange}
  />
);
```

But the value I get in my date state are just event objects. Can somebody help, please?

**Comment by shahabyazdi** [comment]
You can use the toDate() or valueOf() methods for this purpose.

```javascript
onChange={(dateObjects) => {
    setDates(dateObjects.map((dateObject) => dateObject.toDate()));
}}
```

But this is not optimal and it is better to do it only [when necessary](https://shahabyazdi.github.io/react-multi-date-picker/installation/#important-notes)

Please see [this](https://codesandbox.io/s/adoring-ardinghelli-4xfvo?file=/src/App.js) example and let me know if you have any problems.

Also, if you want to learn more about DateObject, you can click [this link](https://shahabyazdi.github.io/react-multi-date-picker/date-object/).

**Comment by jessduran** [comment]
This is exactly what I needed. Thank you very much!

**Comment by shahabyazdi** [comment]
You're welcome.
