### ISSUE TITLE
[Bug] Styling days creates empty boxes for the last few dates in the calendar month

### ISSUE THREAD

**Issue by WebDev-Akhil** [shahabyazdi/react-multi-date-picker#42]
In the documentation in[ map days](https://shahabyazdi.github.io/react-multi-date-picker/map-days/), under 'Styling Days', there is an example on how to do custom styling. 

Problem - Selecting the last few dates in the months creates empty styled boxes in the upcoming month. This applies to -> No of empty boxes at the start of the upcoming month == number of dates at the end of present month

Example - 

![image](https://user-images.githubusercontent.com/25116883/119364571-f1aa6080-bca6-11eb-8efe-88d2a46088b7.png)

In the above example, I have selected the date "May 30"

![image](https://user-images.githubusercontent.com/25116883/119364942-5b2a6f00-bca7-11eb-9a09-33b4d443f8ed.png)

Here, it can be observed that an empty box is formed in the following month at the start of dates (under sunday)

**Comment by WebDev-Akhil** [comment]
This is also happening the other way around. Selecting the first few dates of the upcoming month creates empty boxes in the previous month. 

![image](https://user-images.githubusercontent.com/25116883/119375038-3b4c7880-bcb2-11eb-8c64-5003e9c97ec2.png)

Here I have selected June 2nd, which created an empty box at the end of May.

![image](https://user-images.githubusercontent.com/25116883/119375205-7484e880-bcb2-11eb-8e1d-44ae78eb6877.png)

**Comment by shahabyazdi** [comment]
Thank you very much for reporting this bug.
I will try to solve this problem tomorrow.

**Comment by shahabyazdi** [comment]
The bug you mentioned is fixed in v2.9.1.

https://shahabyazdi.github.io/react-multi-date-picker/map-days/#styling-days

**Comment by WebDev-Akhil** [comment]
Tested, all good now. Thanks!
