### ISSUE TITLE
[Feature] Ability to remove 'seconds' from time picker

### ISSUE THREAD

**Issue by WebDev-Akhil** [shahabyazdi/react-multi-date-picker#43]
Problem - The time picker plugin when used in the date-picker, creates the ability to add time but most of the times, we don't really need 'seconds' input in practical cases. I tried removing "SS" from Date Picker's format prop `(format = "D MMMM YYYY, hh:mm A")` but it only removes seconds from the date picker's input label but doesn't remove the second's input from time-picker 

Solution - 

![image](https://user-images.githubusercontent.com/25116883/119377709-54a2f400-bcb5-11eb-9978-4ec092272cd6.png)

So there should be a custom prop for <TimePicker>, something like, 

```
<TimePicker
isSeconds = false //A custom prop which removes seconds input field
>

or 

<TimePicker
format="HH:MM" //custom format to remove seconds. (In this case, it should also override the main picker's format)
>
```

**Comment by shahabyazdi** [comment]
Thanks for mentioning it.
I will work on it.

**Comment by shahabyazdi** [comment]
Your suggested feature was added to the [time picker](https://shahabyazdi.github.io/react-multi-date-picker/other-pickers/#hiding-seconds) & [analog time picker](https://shahabyazdi.github.io/react-multi-date-picker/plugins/analog-time-picker/#hiding-seconds).

```javascript
<TimePicker hideSeconds />
```

**Comment by WebDev-Akhil** [comment]
Working fine. Thanks for adding it!

**Comment by shahabyazdi** [comment]
You're welcome.
