### ISSUE TITLE
[Question] How to add multiple onChange events in DatePicker?

### ISSUE THREAD

**Issue by WebDev-Akhil** [shahabyazdi/react-multi-date-picker#44]
```
import React, { useState } from "react"
import { DatePicker } from "react-multi-date-picker"

type DateProps = {
    updateDate : (date : Date) => void,
}

export function DateTimePIcker = (props : DateProps) => {
 const [date, setDate] = useState(new Date())

  return (
    <DatePicker 
         value={date}
         onChange={setDate}     // onChange={props.updateDate}
    />
  )
}
```

In the above example, if `onChange` is set to `setDate`, then whenever the date is changed by the user, it updates the state. If  `onChange` is set to `props.updateDate`, then it updates the preset value in a parent component

Now, how to update both setValue and props passed at the same time? 

I tried the below but they didn't work -

`onChange={setDate && props.updateDate}
`

using multiple event handlers,

```
onChange={() => {
        eventHandler1()
        eventHandler2()
}}

const eventHandler1 = (date) => setDate(date)
const eventHandler2 = () => props.updateHardDeadline
```

**Comment by shahabyazdi** [comment]
Try this:
```javascript
onChange={date => {
     setDate(date)
     props.updateDate(date)
}}
```

**Comment by shahabyazdi** [comment]
Also a better way is to move the date and setDate to the parent component.

```javascript
import React, { useState } from "react"
import DatePicker from "react-multi-date-picker"

export default ParentComponent(){
    const [date, setDate] = useState(new Date())

    return(
       <ChildComponent date={date} setDate={setDate} />
    )
}

function ChildComponent({ date, setDate}){
   return(
      <DatePicker value={date} onChange={setDate} />
   )
}
```

**Comment by WebDev-Akhil** [comment]
Yes! Thanks alot! 😊

**Comment by shahabyazdi** [comment]
You're welcome

**Comment by WebDev-Akhil** [comment]
> Try this:
> 
> ```js
> onChange={date => {
>      setDate(date)
>      props.updateDate(date)
> }}
> ```

This works but when I add multiple prop updates to the onChange, only setDate and the last one in the stack get executed. Middle ones don't get executed

Scenarios - 

```js
onChange={date => {
      setDate(date) // executes
      props.updateDateAtX(date) // executes
 }}

```
```js
onChange={date => {
      setDate(date) //executes
      props.updateDateAtX(date) // doesn't execute
      props.updateDateAtY(date) // executes
 }}
```

```js
onChange={date => {
      setDate(date) // executes
      props.updateDateAtY(date) // doesn't execute
      props.updateDateAtX(date) // executes
 }}
```

```js
onChange={date => {
      setDate(date) // executes
      props.updateDateAtX(date) // doesn't execute
      props.updateDateAtY(date) // doesn't execute
      props.updateDateAtZ(date) // executes
 }}
```

We can observe that only setDate and the last one in the stack gets executed. Middle ones don't get executed. I need this because I'm using multiple dateTimePickers and changing one date should dynamically update other dates too

**Comment by shahabyazdi** [comment]
Hello
I'm very sorry that you are experiencing this.
But it is unlikely that your problem is from onChange. ([see this example](https://codesandbox.io/s/competent-smoke-yel6o?file=/src/App.js))
Please provide your code in codesanbox so I can check it.

**Comment by WebDev-Akhil** [comment]
> Hello
> I'm very sorry that you are experiencing this.
> But it is unlikely that your problem is from onChange. ([see this example](https://codesandbox.io/s/competent-smoke-yel6o?file=/src/App.js))
> Please provide your code in codesandbox so I can check it.

Sorry for the very late reply. Yes, it was my mistake. The function I passed into onChange was accepting only one value change at a time. I changed it and it worked. 

Here is what I did, in case if some other person who might visit this page wants to know. So the parent Component is a class-based component. 

Before - 

```js
// In childComponent, (i.e. timePicker.jsx)
onChange={date => {
      setDate(date) // executes
      props.updateDateAtX(date) // doesn't execute
      props.updateDateAtY(date) // doesn't execute
      props.updateDateAtZ(date) // executes
 }}

// In Parent Component,
updateDates = (type : string, value) => {
        this.props.updatePage({
            ...this.props.page,
            "dates" : {
                ...this.props.page.dates,
                [type] : value,
            },
        })
    }

updateDateAtX = (value) => this.updateDates("X", value)
updateDateAtY = (value) => this.updateDates("Y", value)
updateDateAtZ = (value) => this.updateDates("Z", value)
```
After - 

```js
// In childComponent, (i.e. timePicker.jsx)
onChange={date => {
      setDate(date) // executes
      props.updateDateAtXYZ(date) // executes
 }}

// In Parent Component,
updateDatesAtXYZ = (type : string, value) => {
        this.props.updatePage({
            ...this.props.page,
            "dates" : {
                ...this.props.page.dates,
                "X" : value,
                "Y" : value,
                "Z" : value,
            },
        })
    }
```
