### ISSUE TITLE
[Bug] DatePicker is not mobile responsive when used with TimePicker in default position (placed right side)

### ISSUE THREAD

**Issue by WebDev-Akhil** [shahabyazdi/react-multi-date-picker#45]
DatePicker when used with an Analog_time_picker, is mobile-friendly whereas when DatePicker is used with time_picker, it doesn't display properly on small screens. 

![image](https://user-images.githubusercontent.com/25116883/120229804-dbbc1300-c245-11eb-9f00-de3a2b38bc6f.png)
**Figure-1 (Displays properly)**

![image](https://user-images.githubusercontent.com/25116883/120229849-f5f5f100-c245-11eb-97b5-caf15a4558d6.png)
**Figure-2 (Doesn't display properly)**

In the above images, we can see that when a datePicker is used with an Analog Time Picker displays properly but when used with a timePicker, cuts off the right side content

**Code used -** 

```
import React, { useState } from "react";
import DatePicker, { DateObject } from "react-multi-date-picker";
// import TimePicker from "react-multi-date-picker/plugins/analog_time_picker";
import TimePicker from "react-multi-date-picker/plugins/time_picker";

export default function App() {
  let [date, setDate] = useState(new DateObject());

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <DatePicker
        value={date}
        onChange={setDate}
        calendarPosition="bottom-center"
        plugins={[<TimePicker hideSeconds />]}
      />
    </div>
  );
}
```
**Actions to replicate the scenario -**

1. Go to this  [CodeSandbox](https://codesandbox.io/s/sharp-ardinghelli-77qxw?file=/src/App.js)
2. In the right-side preview panel, beside the URL container, click on the "Open in new window" icon 
3. Preview opens in a new window. Right Click > Inspect > choose a mobile (like iPhone X)

**Comment by shahabyazdi** [comment]
It is best to place TimePicker at the `bottom ` of the Calendar.
![image](https://user-images.githubusercontent.com/18695593/120272554-88d47100-c2c2-11eb-9314-e2eb81846960.png)

Placing the TimePicker to the `left` or `right` of the Calendar creates too much space in the `top` and `bottom` of the TimePicker, which is not desirable.

![image](https://user-images.githubusercontent.com/18695593/120271580-d223c100-c2c0-11eb-8289-08d050c2ac54.png)

For the problem you mentioned, I can add `style` and `className` props, so the user can adjust the TimePicker width if needed.
___
Also, I'm glad to know your idea for resolving the empty spaces I mentioned.

**Comment by WebDev-Akhil** [comment]
> Also, I'm glad to know your idea for resolving the empty spaces I mentioned.

I think it is okay to have that white space as it is a decision taken by the user not to have an analog clock at the top and want to place the picker at the right side instead of the bottom. You can try adding a label called "Preview" under the picker, where that date and time is dynamically displayed when onlyTimePicker is used. (..but I think it is okay to have white space for now).


The only suggestion I have is to reduce the time taken to show the initial tooltip. The first toolpick is taking more than 2 seconds to show up, which is a bit more.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/25116883/120858837-47221f80-c57b-11eb-81bc-bf205f5380a4.gif)

**Comment by shahabyazdi** [comment]
Hello and thanks for the suggestion.
You can now change the time picker width by installing v2.9.3.
But the speed of displaying the title in HTML is related to the browser settings and I can not do anything about it. 

> [No, there's no way. The title attribute is implemented in a browser dependent fashion. ](https://stackoverflow.com/a/9150826/11825348)

But I put a trick on the demo page that might be useful.

1- [Styling TimePicker](https://shahabyazdi.github.io/react-multi-date-picker/plugins/time-picker/#styling-timepicker)
2- [Custom Tooltip](https://shahabyazdi.github.io/react-multi-date-picker/map-days/#custom-tooltip)

**Comment by WebDev-Akhil** [comment]
No worries, thanks!
