### ISSUE TITLE
bg-dark styling issue with min/max dates

### ISSUE THREAD

**Issue by AshenCat** [shahabyazdi/react-multi-date-picker#46]
![image](https://user-images.githubusercontent.com/8600507/121123637-8e194a80-c7f1-11eb-9414-b64dd4c47007.png)
![image](https://user-images.githubusercontent.com/8600507/121123668-9b363980-c7f1-11eb-8444-3a7ca1a4a3da.png)

also, typo here: https://github.com/shahabyazdi/react-multi-date-picker/blob/ca48158165581593226c2093b3012828e8210a8e/website/src/docs/props.js#L365

**Comment by shahabyazdi** [comment]
I just wanted to say that I fixed it, but I realized that you closed this issue!
Sorry for the late reply.

**Comment by AshenCat** [comment]
I was about to use default theme instead but now i can now use it. Thank you for fixing it!

**Comment by shahabyazdi** [comment]
You're welcome 🙂
