### ISSUE TITLE
Reset date picker to empty date in mobile. 

### ISSUE THREAD

**Issue by lharby** [shahabyazdi/react-multi-date-picker#48]
Hi. Not sure if this is a bug as such. This seems to be for a mobile implementation. 

We are trying to create a version of the DatePicker where we filter data based on the input date (using a month calendar) but we're also trying to implement a reset/clear all function. We reset the trigger button property, remove the current selected date and use placeholder text. 

The issue is that the next time the calendar is launched the previously selected date is still active. 

Example:
Select May 2019. 
Execute Clear All.
Open new DatePicker, selected date is still shown as May 2019. 

I thought there was a `selectedDate `prop (which was different to the DatePicker value prop, but I can't see it now. 

I believe on the desktop version we can use an input trigger and empty this value which seems to clear the current selected date. 

TIA

**Comment by shahabyazdi** [comment]
Hi.
Do you keep the date picker value in a state?
Does your reset button delete the date picker value from the state?
I put an example of a date picker in a mobile mode in [code sandbox](https://codesandbox.io/s/interesting-thunder-qge26?file=/src/App.js) which is deleting the date picker value by pressing the reset button, please check it out and tell me if you saw your problem with that code. or, if possible, send me the part of your code that is causing the problem.
Thank you.

**Comment by lharby** [comment]
Thank you. I thought this functionality was available and I can see it working in your sandbox. I think it is to do with our implementation. So please close this ticket. I will try and resolve in our app.

**Comment by shahabyazdi** [comment]
I hope you're problem is solved.
Please reopen this if the problem was related to the date picker.
