### ISSUE TITLE
How to get each data of range selection

### ISSUE THREAD

**Issue by Shawnfoto** [shahabyazdi/react-multi-date-picker#5]
I selected 1/1~1/5, but it only showed 1/1, 1/5 on the form of dates.
May I ask how to get each data(1/1, 1/2, 1/3, 1/4, 1/5) of range selection?

**Comment by shahabyazdi** [comment]
In range mode, only the start and end dates are given, because the user may select a whole year and it is not optimal to store the whole year in memory.
You can use a for loop like this [example ](https://codesandbox.io/s/festive-mendeleev-yzeic?file=/src/App.js)to get each days

**Comment by Shawnfoto** [comment]
Thank you.

**Comment by shahabyazdi** [comment]
You're welcome
