### ISSUE TITLE
How to disable the current date selection on calendar open?

### ISSUE THREAD

**Issue by nizniz187** [shahabyazdi/react-multi-date-picker#50]
In single mode, when I click an input and trigger the calendar open, the current date is always selected on default if the input value is empty.
Is there a way to disable this feature, and make the input value remain empty until the user select one?

**Comment by shahabyazdi** [comment]
Yes, you can do this by setting an empty object as the default value.

```javascript
 const [date, setDate] = useState({});

 return (
   <DatePicker
     value={date}
     onChange={(date) => {
       setDate(date || {});
     }}
   />
 );

```

https://codesandbox.io/s/beautiful-tesla-sgrnx?file=/src/App.js:119-281

**Comment by nizniz187** [comment]
Worked like a charm!! Thank you very much.

**Comment by shahabyazdi** [comment]
You're Welcome
