### ISSUE TITLE
Calendar fullYear no longer working

### ISSUE THREAD

**Issue by ivanpaul7** [shahabyazdi/react-multi-date-picker#51]
Hi,
The Calendar fullYear attribute is no longer working.

**Comment by shahabyazdi** [comment]
Hi , The fullYear prop is availble in the version 3.0.0 wich is currently in dev mode , if you want to use full year view please install v3.0.0-dev.1 

```
npn i --s react-multi-date-picker@dev
```

**Comment by ivanpaul7** [comment]
Thank you a lot!

**Comment by shahabyazdi** [comment]
You're Welcome.
