### ISSUE TITLE
Close picker

### ISSUE THREAD

**Issue by AliBayatMokhtari** [shahabyazdi/react-multi-date-picker#52]
How to close date picker with today onClick event in toolbar? and by the way, thanks for this great library :))

**Comment by shahabyazdi** [comment]
Hi
Thank you for your comment.
Unfortunately, there is no direct way to do this.
But you can do it by using a  ref for date picker and writing a function to compare dates.

[Here is an example](https://codesandbox.io/s/elastic-chebyshev-2obso?file=/src/App.js) of how to close a calendar by clicking on today button, please check it and feel free to contact me  If you have any questions.
