### ISSUE TITLE
How to limit to a maximum of 7 days in multiple mode

### ISSUE THREAD

**Issue by superw-123** [shahabyazdi/react-multi-date-picker#53]
Expected：
<img width="382" alt="日期" src="https://user-images.githubusercontent.com/69564891/126423129-92a19448-2f2e-4957-b81c-6ff4d8a47da6.png">

My method：
const {defaultDate} = props;
const [isExceedMax, setIsExceedMax] = useState(false);
const MyPlugin = () => {
        const dom = isExceedMax ? <Alert message="最多可选7天" type="warning" showIcon /> : null;
        return dom;
 };
const onChangeDate = dateStr => {
        if (dateStr.split(',').length > maxDataLen) {
            setIsExceedMax(true);
        } else {
            console.log('update props defaultDate');
        }
};
<DatePicker
                animation
                multiple
                arrow={false}
                value={defaultDate}
                plugins={[<MyPlugin position="top" />, <DatePanel header="已选日期" />]}
                format={'YYYYMMDD'}
                onChange={
                    array => {
                        onChangeDate(array.join(','));
                    }
                }
                render={<InputIcon />}
/>
 
_plugins: MyPlugin position="top", DatePanel header="已选日期"
render: InputIcon_

problem:
after selected 7 days,  can continue selected

**Comment by shahabyazdi** [comment]
You can do this by placing a condition to check the number of dates in the onChane method.
```javascript
const [value, setValue] = useState([])

<DatePicker
   multiple
   value={value}
   onChange={array=>{
      if(array.length > 7) return

      setValue(array)
   }}
/>
```

**Comment by shahabyazdi** [comment]
I just realized that you want to alert the user if the selected dates are more than 7 days with a plugin.
In this example you can see how to do it:

https://codesandbox.io/s/charming-wilbur-3vs17?file=/src/App.js

**Comment by superw-123** [comment]
> I just realized that you want to alert the user if the selected dates are more than 7 days with a plugin.
> In this example you can see how to do it:
> 
> https://codesandbox.io/s/charming-wilbur-3vs17?file=/src/App.js

thanks! That's what I expected，the problem is solved
