### ISSUE TITLE
How to set another format in input?

### ISSUE THREAD

**Issue by agkourovanidis** [shahabyazdi/react-multi-date-picker#56]
Is it possible to set the dates in input for date range in a custom format?
For Example: instead of "01/08/2021 ~ 08/08/2021" something like this: "Sun. 01 Aug ~ Sun. 01 Aug (7 nights)"
Thanks in advance

**Comment by shahabyazdi** [comment]
Yes, you can do something like this:

https://codesandbox.io/s/pedantic-engelbart-mhjv1?file=/src/App.js

**Comment by agkourovanidis** [comment]
Greate date picker, thanks a lot

**Comment by shahabyazdi** [comment]
You're welcome.
