### ISSUE TITLE
How to prevent calendar marking event?

### ISSUE THREAD

**Issue by mannoeu** [shahabyazdi/react-multi-date-picker#57]
I intend to do a recurrence check when marking a date in the multiple calendar, but the onChange event always returns the array with the clicked date already contained and always marks it in the calendar before the setState in its value=[]

Even being a controlled component, values ​​seem to be ignored by the calendar, which ends up setting the clicked date even without the date being in the array

I'm using onFocusedDateChange to capture the clicked date and do the validation before adding to the date array and in fact it isn't added, but the calendar is checked.

```
const [dates, setDates] = useState([]);

<DatePicker 
  multiple
  value={dates}
  onChange={() => {}}
  onFocusedDateChange={(dateFocused, dateClicked) => {
     validate(dateClicked.format("YYYY/MM/DD"))
  }}
/>
```

**Comment by shahabyazdi** [comment]
The reason is the existence of an internal state in the component.
You can use one of the following examples to validate your dates:

https://codesandbox.io/s/blissful-smoke-04uq7?file=/src/App.js

**Comment by mannoeu** [comment]
> The reason is the existence of an internal state in the component.
> You can use one of the following examples to validate your dates:
> 
> https://codesandbox.io/s/blissful-smoke-04uq7?file=/src/App.js

Example 3 seems perfect to me. But it doesn't work for me, my data array necessarily needs to save data using moment(), which doesn't seem to be accepted by the component.

My set state depends on informing further if the date is valid or not the reason, is there any way for the component to accept an array of instances of moment() ?

**Comment by mannoeu** [comment]
I managed to make a small change to your example. Instead of using onChange, I continued using onFocusedDateChange. I captured the dateClicked and performed my validation on it. If this date already exists in my array, I filter to remove it, if it doesn't exist and pass validation, I add it to the array.

To be able to use it with moment, in my values ​​I pass an array of filtered moment() instances so that they are formatted.

```
const [dates, setDates] = useState([
moment("2021/04/04"),
moment("2021/04/05")
]);

<DatePicker 
  value={dates.map(date => date.format("YYYY/MM/DD"))}
  onFocusedDateChange={(dateFocused, dateClicked) => {
    handleDateChange(dateClicked);
  }
/>
```

And then in handleDateChange I perform the validation bringing back to instance of moment()

```

const handleChangeDate = (dateObj) => {
    const date = moment(dateObj.format("YYYY/MM/DD"));
    const isValid = validateRecurrence(date);
    .
    .
    .
}
```

In my validateRecurrence function I return an object

```
 return {
        valid: true, // Whether it is a valid date in the recurrence range
        error: "", // Error message
        hasDeleted: true, // If it exists in the array
        date: updatedDates, // Updated date array for removal case or a single date for addition case.
 };
```

Thank you for this lib, its awesome!
