### ISSUE TITLE
Is it possible to pick multi date in Calendar fullYear???

### ISSUE THREAD

**Issue by shinu0720** [shahabyazdi/react-multi-date-picker#58]
i did not found the document about this.
is it possible to pick multi date in Calendar fullYear???

**Comment by shahabyazdi** [comment]
Sure, you can use multiple prop to enable multiple mode.
```javascript
<DatePicker 
   fullYear
   multiple
/>
```

**Comment by shinu0720** [comment]
thank you
i will try it
