### ISSUE TITLE
Publish the type interface

### ISSUE THREAD

**Issue by susiyaki** [shahabyazdi/react-multi-date-picker#59]
Thank you nice module.
When I'm using this library on Typescript project, I thought I wanna use `CalendarProps` and `DatePickerProps`.

If aren't there especial reason, export above interfaces.

**Comment by shahabyazdi** [comment]
If I get you're point correctly, you want me to export the calendar and datepicker props.
I will do that as soon as I access to my pc.

**Comment by susiyaki** [comment]
@shahabyazdi 
It's correct! Sorry for the incomprehensible🙏

**Comment by shahabyazdi** [comment]
DatePicker & Calendar props are exported.
Please upgrade to v3.1.2 to use them.

**Comment by susiyaki** [comment]
@shahabyazdi Thank you!

**Comment by shahabyazdi** [comment]
You're welcome. 🙂
