### ISSUE TITLE
minDate and maxDate doesn't work

### ISSUE THREAD

**Issue by Shawnfoto** [shahabyazdi/react-multi-date-picker#6]
Hi shahabyazdi,

I found a problem that when I changed minDate, it work, but changed both minDate and maxDate dynamically, it didn't work.
[https://codesandbox.io/s/range-mode-forked-2z3ex?file=/src/App.js](url)

DatePicker can work, but Calendar can't work.

**Comment by shahabyazdi** [comment]
Thanks for reporting this bug.
Give me some time to solve it.

**Comment by shahabyazdi** [comment]
The bug you mentioned seems to be fixed, please install v1.8.1 and check to see if your problem has been resolved or not.

Also regarding the previous issue:

I added the "eachDaysInRange" Prop, which you can enable it to see the dates between start and end date in the dates panel.
And to get every single date between the start and end dates, I embedded the "getAllDatesInRange" function into DatePicker, so it can be used by other users if they have the same problem.

here is the [codesandbox](https://codesandbox.io/s/range-mode-yzeic?file=/src/App.js)

**Comment by Shawnfoto** [comment]
It's work, thank you.

**Comment by shahabyazdi** [comment]
You're welcome .
Please let me know if you have any other problem
