### ISSUE TITLE
Inability to remove dates out of range in DatePanel

### ISSUE THREAD

**Issue by henry132109** [shahabyazdi/react-multi-date-picker#62]
We are writing a booking system that requires the users to book, say 1 week in advance, the minDate prop is really convenient and adopting it is a smooth process.

However in some situation where such dates must be changed within the last week, the "invalid" dates doesn't show up in either the DatePanel or the DatePicker and they cannot be removed. On a sidenote it's a good thing that the picker doesn't automatically remove old dates; otherwise there'll be data loss.

My thought is to still show them in the DatePanel and allow only removal so out of range dates can still be displayed/saved if they're already there but not added.

**Comment by shahabyazdi** [comment]
If I understand correctly, you want to display dates that are outside the min/max date in the calendar & datepanel.
To do this, you can set the `onlyShowInRangeDates` prop to `false`.
Please try it and let me know if its work or not.

```javascript
<DatePicker
   onlyShowInRangeDates={false}
/>
```

**Comment by henry132109** [comment]
> If I understand correctly, you want to display dates that are outside the min/max date in the calendar & datepanel.
> To do this, you can set the `onlyShowInRangeDates` prop to `false`.
> Please try it and let me know if its work or not.
> 
> ```js
> <DatePicker
>    onlyShowInRangeDates={false}
> />
> ```

Yup, it worked perfectly :)
Closing this issue now
