### ISSUE TITLE
How to render DataPicker to body

### ISSUE THREAD

**Issue by y327595826** [shahabyazdi/react-multi-date-picker#63]
The mask cannot cover the common header and footer when appearance is set to mobile

**Comment by shahabyazdi** [comment]
Most likely you used a fixed position for your header and footer or set their z-index to more than 100.

To solve this problem, set your footer z-index to less than 100 or set the zIndex property of the datepicker more than the footer z-index value.

See this sandbox for example:
https://codesandbox.io/s/loving-benji-etxn0?file=/src/App.js

**Comment by y327595826** [comment]
> Most likely you used a fixed position for your header and footer or set their z-index to more than 100.
> 
> To solve this problem, set your footer z-index to less than 100 or set the zIndex property of the datepicker more than the footer z-index value.
> 
> See this sandbox for example:
> https://codesandbox.io/s/loving-benji-etxn0?file=/src/App.js

I've tried, but it doesn't work. Because the middle content area is a scrolling area that does not include a common header and footer

**Comment by shahabyazdi** [comment]
Unfortunately, I have no idea until I see your layout.
If possible, put your blank layout in the code sandbox so I can work on it.

**Comment by y327595826** [comment]
Thank you for your answer, I have solved the problem.
Now there is another problem. How do I control the CANCEL and OK buttons in mobile mode?

**Comment by shahabyazdi** [comment]
The Buttons have [specific functionality](https://github.com/shahabyazdi/react-multi-date-picker/blob/75d4ae25e818dcdc6e6ab4ffaacb69d80ab83778/src/components/date_picker/date_picker.js#L384) and can not be controlled from the outside.
If you want to validate the selected dates when the user presses the ok or cancel button, [it is better to do it in the onChange method](https://github.com/shahabyazdi/react-multi-date-picker/issues/57#issuecomment-889177598).

**Comment by y327595826** [comment]
Can I have a parameter that it could be configured the button text in mobile mode？

**Comment by shahabyazdi** [comment]
Sure, I'm working on it now.

**Comment by y327595826** [comment]
I truly appreciate your help in resolving the problem.

**Comment by shahabyazdi** [comment]
Please upgrade to v3.1.3 and use mobileLabels prop for changing the text of action buttons in mobile mode. 

https://codesandbox.io/s/mobile-mode-with-custom-labels-3v9rh?file=/src/App.js:271-283

**Comment by shahabyazdi** [comment]
> how to get the open or close status of the calendar？

I didn't see this part of you're question.
You can use onOpen an onClose props.

https://shahabyazdi.github.io/react-multi-date-picker/events/#onopen
