### ISSUE TITLE
[Feature] Use portals

### ISSUE THREAD

**Issue by gormonn** [shahabyazdi/react-multi-date-picker#66]
For now i use Calendar inside React.Portal with custom input, because i can't use your DatePicker with Portals.

Portals are an important way to display dropdown menus. It is very strange that this method was not provided.

Use case:
Let's say your DatePicker is inside a block with overflow: hidden and limited in height.
In this case, you will not see the calendar, because it will be rendered "outside the visible part of the parent block."
For such cases, it is worth using Portals.

https://reactjs.org/docs/portals.html

**Comment by gormonn** [comment]
PS
Besides rendering through the portal, it is good practice to allow the ref to be passed to the custom portal where the calendar should be rendered.

You can find a good example in the react-select package

**Comment by shahabyazdi** [comment]
Sorry for my late reply.
I will definitely work on it.

**Comment by shahabyazdi** [comment]
The **portal** and **portalTarget** props were added to the package as you suggested.

I have prepared an example for each of them on the demo page, please see them and let me know if there is any problem.

https://shahabyazdi.github.io/react-multi-date-picker/portal/

If you encounter 404 error, refresh the browser to clear your browser's cache.

Thanks again for your suggestion

**Comment by gormonn** [comment]
I found a bug in the implementation.
Clicking on anything inside the calendar except days closes the calendar.
To avoid such problems, I recommend using something like this trick:
https://github.com/Andarist/use-onclickoutside

**Comment by shahabyazdi** [comment]
Let me try to fix this problem without adding a dependency to the package, but if I can't, I will do your suggestion.

**Comment by shahabyazdi** [comment]
The problem you mentioned seems to be fixed in version 3.1.5, please let me know if it doesn't work properly.
