### ISSUE TITLE
نشانه گذاری روز تعطیلی خاص

### ISSUE THREAD

**Issue by mrsh0311** [shahabyazdi/react-multi-date-picker#7]
سلام اقای یزدی چجوری یه روز مشخص که تعطیله رو رنگش رو عوض کنم؟

**Comment by shahabyazdi** [comment]
سلام 
برای شخصی سازی روز ها میتونید از
mapDays
استفاده کنید. [اینجا ](https://shahabyazdi.github.io/react-multi-date-picker/#styling-persian-weekends)یه مثال از نشانه گذاری روز های جمعه هست که میتونید یه نگاهی بهش بندازید
من یه نمونه دیگه هم برای شما آماده کردم که میتونید از [اینجا](https://codesandbox.io/s/thirsty-chebyshev-36654?file=/src/App.js) مشاهدش کنید.
باز هم اگر مورد خاص دیگه ای بود بگید.

**Comment by shahabyazdi** [comment]
فکر کنم مشکلتون رو به طریق دیگه ای حل کردید
اگر سوالی داشتید دوباره این بحث رو باز کنید.

**Comment by mrsh0311** [comment]
> 
> 
> فکر کنم مشکلتون رو به طریق دیگه ای حل کردید
> اگر سوالی داشتید دوباره این بحث رو باز کنید.

سلام دست شما درد نکنه فقط پروپرتی های روز و ماه و سال رو میشه از سرور به صورت ارایه یا ابجکت گرفت؟

**Comment by shahabyazdi** [comment]
ببخشید منظورتون رو درست متوجه نشدم 
شما از سرورتون هر جوری که لازم میدونید میتونید زمان رو بگیرید ولی ورودی 
DatePicker
تون حتما باید یکی از 4 حالت
String, Number, Date , DateObject
باشه
برای اطلاعات بیشتر میتونید مثال های [صفحه دمو](https://shahabyazdi.github.io/react-multi-date-picker/#value-types) رو ببینید.

**Comment by mrsh0311** [comment]
> 
> 
> فکر کنم مشکلتون رو به طریق دیگه ای حل کردید
> اگر سوالی داشتید دوباره این بحث رو باز کنید.

سلام دست شما درد نکنه فقط پروپرتی های روز و ماه و سال رو میشه از سرور به صورت ارایه یا ابجکت گرفت؟

> 
> 
> ببخشید منظورتون رو درست متوجه نشدم
> شما از سرورتون هر جوری که لازم میدونید میتونید زمان رو بگیرید ولی ورودی
> DatePicker
> تون حتما باید یکی از 4 حالت
> String, Number, Date , DateObject
> باشه
> برای اطلاعات بیشتر میتونید مثال های [صفحه دمو](https://shahabyazdi.github.io/react-multi-date-picker/#value-types) رو ببینید.
> 
> مثلا در [این مثال](https://shahabyazdi.github.io/react-multi-date-picker/#multiple-mode-#4) من هر 4 حالت مختلف رو یکجا اوردم.

**Comment by mrsh0311** [comment]
مثلا این مثال که
const [anotherFavoriteDate] = useState(
      new DateObject({
        calendar: "persian",
        year: 1399,
        months: 10,
        day:12
      })
    );
چجوری میتونم مقدار روز رو مثلا به صورت ارایه ای از اعداد بگیرم که بشه از سرور به
صورت ای پی آی دریافت کرد و ریخت تو آرایه و از اون جا چندین مقدار رو خوند

**Comment by mrsh0311** [comment]
مثلا مقدار سال 1399 ماه دهم رو روزها رو چند تاشو با هم تعطیل کرد نه یکی فقط

**Comment by shahabyazdi** [comment]
طبیعتا شما روز هاتون رو داخل سرور هم باید به صورت  آرایه ای از
date
ها ذخیره کنید. یعنی بهتره که به جای ذخیره کردن روز و ماه و سال به صورت جدا ، مقدار هر کدوم از تاریخ هاتون رو بگیرید .  مثلا در مثال بالا که گفتید میتونید مقدار این زمان رو به این صورت بگیرید و در دیتابیستون ذخیره کنید

```javascript
const date = new DateObject({
calendar: "persian",
year: 1399,
month: 10,
day:12
}).valueOf()
``` 
یا اگر پایگاه دادتون 
nosql
باشه بهتره که زمان هاتون رو به این صورت به 
date
جاوااسکریپت تبدیل کنید
```javascript
const date = new DateObject({
calendar: "persian",
year: 1399,
month: 10,
day:12
}).toDate()
``` 

مقدار های مثال اول و دوم به ترتیب اینجوری میشه
1- 1609446600000
2- 2020-12-31T20:30:00.000Z

و در سمت کلاینت همین مقدار هارو دوباره به این صورت به زمان شمسی تبدیل کنید

```javascript
const date  = new DateObject({date:1609446600000,calendar:"persian"})
const anotherDate = new DateObject({date:"2020-12-31T20:30:00.000Z",calendar:"persian"})

```

این دوتا سایت رو هم از گوگل سرچ کردم اگر دوست داشتید مطالعه کنید
[بهترین روش ها جهت ذخیره سازی و نمایش تاریخ و زمان در پایگاه داده](http://bytelearn.ir/post/%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86-%D8%B1%D9%88%D8%B4-%D9%87%D8%A7-%D8%AC%D9%87%D8%AA-%D8%B0%D8%AE%DB%8C%D8%B1%D9%87-%D8%B3%D8%A7%D8%B2%DB%8C-%D9%88-%D9%86%D9%85%D8%A7%DB%8C%D8%B4-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE-%D9%88-%D8%B2%D9%85%D8%A7%D9%86-%D8%AF%D8%B1-%D9%BE%D8%A7%DB%8C%DA%AF%D8%A7%D9%87-%D8%AF%D8%A7%D8%AF%D9%87)
[بهترين روش ها جهت ذخيره سازي و نمايش اطلاعاتي از نوع تاريخ و زمان](http://toralsystem.com/forum/subject.aspx?sid=93&fid=20)

**Comment by shahabyazdi** [comment]
این هم یک مثال عملی

https://codesandbox.io/s/sad-brahmagupta-lb4l0?file=/src/App.js

**Comment by mrsh0311** [comment]
شرمنده هی مزاحم میشم منظور من این سبک کد نویسیه
const [date, setDate] = useState(new DateObject());
    const rooz=[1,2,3,4,5,6]

    const [anotherFavoriteDate] = useState(
      new DateObject({
        calendar: "persian",
        year: 1399,
        month: 10,
        day:12
      }).valueOf()
    );
که مثلا ارایه ای از روز ها حالا اینجا به صورت دستی ولی در دیتا بیس به صورت دیتا 
یعنی ان تا تعطیلی مثل TIME.IR
که هی نخوای دونه دونه وارد کرد

**Comment by shahabyazdi** [comment]
<div dir="rtl">
<p>خواهش میکنم هیچ مزاحمتی نیست .</p>
<p>بزارید من مرحله به مرحله توضیح بدم بعد شما هر قسمتی رو من اشتباه کردم اصلاح کنید</p>
<p>
اول شما باید <b>مقدار</b> (مقدار، نه روز)تاریخ هایی که میخواید در دیتپیکرتون قرمز نشون داده بشه رو در دیتابیستون ذخیره کنید
اگر هم جای مقدار میخواید <b>روز</b> رو (مثلا 1،2،3،4،5)در آرایه بزارید باز مشکلی نداره فقط روال استانداردی نیست
</p>
<p>
حالا ما فرض میکنیم شما داخل یک useEffect یک درخواست به سرورتون میفرستید و آرایه ای از <b>تاریخ ها</b> یا ارایه ای از <b>روز ها</b> رو دریافت میکنید و در یک state ذخیره اش میکنید
</p>
<p>
حالا دیگه همه چیز آماده است تا توسط فانکشن mapDays برسی کنید که اگر روزی که داره در دیت پیکر نمایش داده میشه با روز های داخل آرایه تون همخوانی داره یا نه تا کلاس یا استایل اون روز رو به حالت دلخواهتون در بیارید
</p>
<p>
روال کار mapDays این هست که دونه دونه روز هایی که داره در تقویم <b>رندر</b> میشه رو به شما میده و ازتون پراپرتی پس میگیره و روی اون span ای که عدد روز داخلش نمایش داده میشه اعمال میکنه
</p>
<p>
توی بحث ما شما میخوای کلاس اون span رو به rmdp-weekend تغییر بدید ، یعنی قرمزش کنید ،
</p>
<p>
چون شما تمایل دارید ارایه تون به صورت عددی باشه بیاید فرض کنیم شما با درخواست به سرورتون و پردارشش متوجه شدید که میخواید از سال 1399 و ماه دی روز های 4 ، 5 ، 6 و 7 اش رو قرمز کنید ، پس داشته هاتون تا اینجا ایناست :
</p>
</div>

```javascript
const year = 1399
const monthNumber = 10
const days = [4, 5, 6, 7] 
```

<div dir="rtl">
حالا وقتشه که این  مقدار ها رو در mapDays برسی کنیم :
</div>

```javascript
<DatePicker
   calendar="persian"
   local="fa"
   mapDays={({date})=>{
      //تاریخی که میخواد رندر شه اول میاد اینجا تا ببینه پراپرتی ای قراره بهش اضافه شه یا نه
      //ما اینجوری این تاریخ رو برسی میکننیم ببینیم همون تاریخی هست که ما میخوایم یا نه:
      if(date.year === year && date.month.number === monthNumber && days.includes(date.day)){
         //اگر این شرط برقرار شد پس ما کلاس دلخواهمون رو ارسال میکنیم
         return { className:"rmdp-weekend"}
      }
   }}
/>
```
اگر شما این کار رو درست انجام بدید باید یک همچین چیزی رو در تقویم ببینید»

![image](https://user-images.githubusercontent.com/18695593/103166262-8f534e00-4835-11eb-9dbd-52b4147464f9.png)

**Comment by mrsh0311** [comment]
دستتون درد نکنه

**Comment by shahabyazdi** [comment]
شرمنده نتونستم کمکی کنم

**Comment by mrsh0311** [comment]
شرمنده یه سوال دیگه فقط همین سال و ماه هم میشه این کارو کرد

**Comment by shahabyazdi** [comment]
<div dir="rtl">
<p>خواهش میکنم</p>
<p>به نظر من تا وقتی به نتیجه نرسیدی هر سوالی داری بپرس</p>
<p>درمورد اینکه گفتی سال و ماه هم به صورت آرایه در بیارید دیگه خیلی کارتون سخت میشه مثلا این مثال رو نگاه کن :</p>
</div>

```javascript
const years = [1399,1400]
const months = [1,3,5,7]
const days = [4,5,6,7,8,9]
```


<div dir="rtl">
<p>الان دیکه اصلا مشخص نیست کدوم روز مال کدوم ماه هست، کدوم ماه مال کدوم سال هست، خیلی کارتون سخت میشه.</p>
<p>همونطور که قبلا هم گفتم بهترین راه اینه که  آرایه ای از تاریخ هارو جایگزین کنید</p>
<p>من یه سرچ تو گوگل کردم و از <a href="https://tafrihyab.com/media/showarticle/413/%D8%AA%D8%B9%D8%B7%DB%8C%D9%84%D8%A7%D8%AA-%D8%B1%D8%B3%D9%85%DB%8C-%D8%B3%D8%A7%D9%84-1399-%D9%87%D8%AC%D8%B1%DB%8C-%D8%B4%D9%85%D8%B3%DB%8C-">اینجا</a> تعطیلات رسمی سال 99 رو برای شما یه صورت آرایه نوشتم که اینجوری شد :</p>
</p>
</div>

```javascript
const holidays = [
  "1399/01/01",
  "1399/01/02",
  "1399/01/03",
  "1399/01/04",
  "1399/01/12",
  "1399/01/13",
  "1399/01/20",
  "1399/02/25",
  "1399/03/04",
  "1399/03/05",
  "1399/03/14",
  "1399/03/15",
  "1399/03/28",
  "1399/05/10",
  "1399/05/18",
  "1399/06/07",
  "1399/06/08",
  "1399/07/16",
  "1399/07/24",
  "1399/07/26",
  "1399/08/13",
  "1399/08/14",
  "1399/10/27",
  "1399/11/22",
  "1399/12/07",
  "1399/12/21",
  "1399/12/29",
  "1399/12/30"
];
```
<div dir="rtl">
حالا میشه خیلی راحت و بی دردسر این تاریخ هارو در دیت پیکرتون برسی کنید:
</div>

```javascript
<DatePicker
   calendar="persian"
   mapDays={({ date }) => {
     let props = { className: "rmdp-weekend" };

     //in shart baraye ruz haye jomast
     if (date.weekDay.index === 6) return props;

     //in shart baraye tatilate rasmi
     if (
       holidays.includes(
         new DateObject(date).setLocal("en").format("YYYY/MM/DD")
       )
     )
       return props;
   }}
/>
```
<div dir="rtl">
<p>الان خروجی این کار دقیقا باید همونی بشه که شما میخواید ، چون تو پیام های بالاتون به سایت time.ir اشاره کرده بودید</p>
</div>

![image](https://user-images.githubusercontent.com/18695593/103198587-ef152c00-48fd-11eb-8940-ebe6cde8c1d5.png)


<div dir="rtl">
<p>
همین مثال رو من براتون در <a href="https://codesandbox.io/s/sad-brahmagupta-lb4l0?file=/src/App.js:709-1165">codesandbox</a> هم آماده کردم که میتونید مشاهدش کنید.
</p>
</div>

**Comment by mrsh0311** [comment]
ممنون دست شما درد نکنه

**Comment by shahabyazdi** [comment]
خواهش میکنم
