### ISSUE TITLE
Could I set the precision on TimePicker

### ISSUE THREAD

**Issue by y327595826** [shahabyazdi/react-multi-date-picker#72]
Hi! Excuse me, I have a need now.
The TimePicker only needs to set hours

**Comment by shahabyazdi** [comment]
Hello, I'm very sorry that I replied late
This is not possible with current plugins.
You must create a plugin for this case.

https://shahabyazdi.github.io/react-multi-date-picker/plugins/docs/
https://github.com/shahabyazdi/react-multi-date-picker/blob/master/src/plugins/time_picker/time_picker.js
