### ISSUE TITLE
Open year selection first, then month then day

### ISSUE THREAD

**Issue by lorenzoalfieri** [shahabyazdi/react-multi-date-picker#74]
Hi, is there a way to open first the year select, then the month one and for last the day one.

I want to let user select this way.

**Comment by shahabyazdi** [comment]
Hello.
Unfortunately I haven't implemented this feature.

**Comment by lorenzoalfieri** [comment]
I'll try to make a pull request if you are fine with it

**Comment by shahabyazdi** [comment]
I'm ok with that.
Just if you want to work on this feature, please do it in such a way so that the user can enable or disable it by making a Prop true and false.
So that if someone (includes me!) prefers, they can use the current mode.
