### ISSUE TITLE
How to disable specific dates

### ISSUE THREAD

**Issue by TheBestMoshe** [shahabyazdi/react-multi-date-picker#75]
Is there any way to disable a list of dates without using `minDate` and `maxDate`?

My use case is that I have some dates that are no longer available and don't want any other users to choose these dates.

**Comment by TheBestMoshe** [comment]
I found the `mapDays` prop which [according to the docs](https://shahabyazdi.github.io/react-multi-date-picker/map-days/#:~:text=The%20Props%20you%20return%20can%20contain%20all%20the%20Props%20that%20a%20span%20element%20accepts%2C%20plus%20two%20other%20properties%20that%20I%20have%20added%20to%20them%2C%20which%20are%3A) accepts a `disabled` field. I can confirm this works and disables the day.

However, it seems like the libraries types do not accept these additional fields. The defined return type is `HTMLAttributes<HTMLSpanElement> | void`.

I created #76 to fix this.

**Comment by shahabyazdi** [comment]
Thank you, I will publish new version tomorrow.

**Comment by TheBestMoshe** [comment]
Thanks!
