### ISSUE TITLE
Disable Date & Month with Position Right Timepicker

### ISSUE THREAD

**Issue by ayush-lal** [shahabyazdi/react-multi-date-picker#77]
How am I able to disable the following date and month when time picker's position is right - as a result of disabling it, the time picker should be centered:

![image](https://user-images.githubusercontent.com/41420385/141213769-12e97f34-60d6-42d1-94dd-7e98a634d7a4.png)

**Comment by shahabyazdi** [comment]
Please give me a day to work on it.

**Comment by ayush-lal** [comment]
Thank you so much!

**Comment by ayush-lal** [comment]
@shahabyazdi any update on this?

**Comment by shahabyazdi** [comment]
I apologize for being a little late.
Please upgrade to 3.2.0 and set the `header` prop for TimePicker to `false`.

```javascript
<DatePicker
        plugins={[<TimePicker header={false} />]}
      />
```

**Comment by ayush-lal** [comment]
Amazing and works perfectly! Thank you heaps for sorting this out
