### ISSUE TITLE
Support Umm al-Qura calendar

### ISSUE THREAD

**Issue by tonydiaz** [shahabyazdi/react-multi-date-picker#78]
Would it be possible to use this package for the Umm al-Qura calendar?

For the Umm al-Qura calendar today would be the 6th:
<img width="407" alt="Screen Shot 2021-11-11 at 3 28 21 PM" src="https://user-images.githubusercontent.com/7145340/141364516-db8cc629-9d82-4433-abde-e51ec0ace58f.png">
https://www.al-habib.info/islamic-calendar/ummulqura/islamic-calendar-ummulqura-2021-ce.htm

**Comment by shahabyazdi** [comment]
The lunar Hijri calendar used in this package follows conventional calculations, but as far as I know, the Umm al-Qura calendar uses astronomical calculations, which I haven't studied.
Technically, if you have access to those calculations, you can create a [custom calendar](https://shahabyazdi.github.io/react-multi-date-picker/calendars/#custom-calendar) for yourself.

**Comment by tonydiaz** [comment]
Thanks for the response! 

I think I could grab the calculation from this other package to make a custom calendar: https://github.com/wajnberg/national-flatpickr/blob/92d1dc01078aeb06d5da34360cadce059c66a351/src/utils/nationalcalendar.ts#L432
