### ISSUE TITLE
Displaying UTC Date/Time Not Working

### ISSUE THREAD

**Issue by ayush-lal** [shahabyazdi/react-multi-date-picker#79]
I am trying to display the current UTC date/time **onOpen** to the DateTime picker however its not working as expected. I am using moment.js for this and I believe that's partly the issue but im not sure:

Before:
![image](https://user-images.githubusercontent.com/41420385/141659404-e25a01d5-099b-4ab0-ae5a-dc934095cf21.png)

After onOpen is triggered (expected UTC date time to be inserted however its only local time):
![image](https://user-images.githubusercontent.com/41420385/141659422-ac57b428-987c-4311-8e33-55776c09484d.png)

`
    <DatePicker
      value={dateTime}
      onOpen={() => setDateTime(moment.utc().format())}
      format="DD/MM/YYYY HH:mm"
    />
`

I can confirm that the dateTime's state contains the new UTC moment value when onOpen is triggered but the picker itself only displays local time.

I have also tried moment.utc().format('DD/MM/YYYY HH:mm') to match the picker format.

Thanks in advance

**Comment by shahabyazdi** [comment]
I did not work much with UTC time and I can only tell you what I am guessing:
When you format the date to a string, it is not possible to detect that date is UTC or not. Unless that data is formatted as an ISO Date String.
Since all incoming dates to this package are converted to DateObject in the first instance, I may have forgotten to check UTC Dates (in which case we are on the side of a bug)
A quick fix for your problem is to replace `moment.utc()` with `new DateObject.toUtc()` and don't convert that date to a string.

https://codesandbox.io/s/morning-snowflake-r2pt6?file=/src/App.js

**Comment by ayush-lal** [comment]
@shahabyazdi that makes sense thanks however there seems to be an expected behaviour with state and the onOpen prop which im using. 

It seems that onOpen prop doesn't update state fast enough for the picker so it ends up displaying local time until onChange is triggered.

Example:
https://codesandbox.io/s/jolly-mestorf-2u0i9?file=/src/App.js

**Comment by shahabyazdi** [comment]
The onOpen prop is triggering before onChange, so as soon as the UTC date is set in the onOpen, a new date comes from onChange and replaces it.to avoid this you can use this solution:

https://codesandbox.io/s/distracted-mendel-4qq7v?file=/src/App.js

**Comment by ayush-lal** [comment]
Hey @shahabyazdi, thanks for the solution and apologies for the delayed response. Im running into a weird issue now where if a component has two DateTimePicker instances running under the same state - adjusting the time on Picker1 won't update Picker2 (vice versa) until a date value is changed. 

Example:
https://codesandbox.io/s/bold-architecture-t9r1n

**Comment by ayush-lal** [comment]
https://user-images.githubusercontent.com/41420385/142192362-cf95b3dd-0cbe-4c26-b264-04068606eda0.mp4

**Comment by ayush-lal** [comment]
@shahabyazdi, just another thing to note. I can confirm that the **onChange** prop is definitely updating the state for both pickers however the picker itself is not updating the new values

**Comment by ayush-lal** [comment]
Creating a seperate issue for this as the original issue here has been resolved
