### ISSUE TITLE
How to get the ref of DatePicker component

### ISSUE THREAD

**Issue by andrejastanojkovic** [shahabyazdi/react-multi-date-picker#8]
I added a button component as a child of the DatePicker component. Than I want to close the open DatePicker by pressing the button.
How can I invoke closeCalendar method or somehow forward the ref to your component?

Thank you in advance,
Best regards

**Comment by shahabyazdi** [comment]
Unfortunately, none of these two issues you mentioned are supported in Datepicker.
But i will try to provide a possibility to open and close Calendar manually in the next version.

**Comment by andrejastanojkovic** [comment]
Thanks a lot for your reply.
When will be the next release?

I tried to create a pull request, but I don't have a permission to do that...
You can just add a outerRef as a input parameter in date_picker.js, and just add:
calendarRef = useRef(outerRef || null);

Thank you in advance,
Best regard

**Comment by shahabyazdi** [comment]
I'm not at my desk right now. If you want a specific time, it will probably be done tomorrow (about 15 hours later).
I thought I would do this with forwardRef and then add open and closeCalendar to it.

```javascript
function DatePicker (props, datePickerRef){
   datePickerRef = datePickerRef || useRef(null)
   .
   .
   .
   if (datePickerRef.current){
      datePickerRef.current.openCalendar = openCalendar
      datePickerRef.current.closeCalendar = closeCalendar
   }
   .
   .
   .
}

export default forwardRef(DatePicker)
```
then you can enter you're ref in DatePicker:
```javascript
<DatePicker ref={myRef} />
```
And close the Calendar in you're click listener

```javascript
<button onClick={()=>{
   myRef.current.closeCalendar()
}}
>
Close
</button>
```
Are you ok with this ?

**Comment by shahabyazdi** [comment]
Package has been updated to version 1.8.6, now you can enter you're ref to DatePicker, as I said it in the previous comment.

**Comment by mrsh0311** [comment]
سلام چجوری روزای تعطیل رو قرمز کنیم تو این لایبرری؟

**Comment by shahabyazdi** [comment]
> سلام چجوری روزای تعطیل رو قرمز کنیم تو این لایبرری؟

سلام پاسخ شما رو همون روز که پرسیدید دادم 
لطفاً لینجا رو ببینید
https://github.com/shahabyazdi/react-multi-date-picker/issues/7

**Comment by andrejastanojkovic** [comment]
Thank you so much! :)
Now works great :)

**Comment by shahabyazdi** [comment]
You're welcome , Good to hear that 🙂

**Comment by andrejastanojkovic** [comment]
Hi Shahabyazdi,

Now from time to time I got this error:
Object doesn't support property or method 'append'
in ForwardRef.

I suppose the error occurred in date_picker.js when you trying to append div on ref:
div.append(a)
div.append(b)

datePickerRef.current.append(div)

Could you just instead of append set appendChild method?

Thank you in advance,
Best regards,
Andreja

**Comment by shahabyazdi** [comment]
Because I completely separated datePickerRef and outerRef. I'm not sure the problem is from there.

```javascript
ref={element => {
   datePickerRef.current = element
   if (outerRef) outerRef.current = element
.
 .
```
Can you send me your DatePicker code, or put it in codesandbox, so that I will be able to check it myself?

**Comment by andrejastanojkovic** [comment]
const datePickerRef = useRef();

<DatePicker
	ref={datePickerRef}
	value={date}
	format="DD MMM YYYY"
	inputClass='custom-input'
	inputMode="none"
	type="input-icon"
	range
	calendarPosition="auto-right"
	mustShowDates={false}
	onChange={setDate}>
	<div
		className="accounts-page__clear-selection"
		onClick={() => {
		        handleDateChange(undefined);
		        datePickerRef.current.closeCalendar();
	        }}>
	<span className="icon-slash-outline"></span>
	    {t('label.clear_selection')}
	</div>
</DatePicker>

That error only appears on InternetExplorer :(
'Object doesn't support property or method 'append'
in ForwardRef.'

**Comment by shahabyazdi** [comment]
Let me check

**Comment by shahabyazdi** [comment]
As you said, ie does not support append.
I replaced append with appendChild and I hope this solves your problem.

8f96eabe59858657819d106e13510a2a679190e8

**Comment by andrejastanojkovic** [comment]
It works now :) 
Great job, thank you one more time :D
I will test more in details today, but I hope it will be ok
