### ISSUE TITLE
handle min/max date on input

### ISSUE THREAD

**Issue by mahboobehsalmani** [shahabyazdi/react-multi-date-picker#81]
I use min/max date props to limit the time user picks but it doesn't handle the time user writes. How can I handle this?

**Comment by shahabyazdi** [comment]
You need a custom input for that.
See the example below:

https://codesandbox.io/s/adoring-resonance-png21?file=/src/App.js

**Comment by mahboobehsalmani** [comment]
It works fine with Gregorian calendar, but with Persian calendar it doesn't. I made a DateObject like this: 

`const maxDate = new DateObject({
    date: "1400/08/25",
    format: "YYYY/MM/DD",
    calendar: persian,
    locale: persian_fa,
  });`

It limits date on datePicker like before but I can enter any date in input.

**Comment by mahboobehsalmani** [comment]
https://codesandbox.io/s/proud-frost-xlec1
Am I using it wrong?
Also in Gregorian  version I still can add number to the end of the date. like this: 2021/11/207777

**Comment by shahabyazdi** [comment]
Also you need to make a persian date in your custom input onchange method , line 49
```javascript
let date = new DateObject({
    date: strDate,
    format: "YYYY/MM/DD",
    calendar: persian,
    locale: persian_fa,
  });

```

**Comment by mahboobehsalmani** [comment]
> Also you need to make a persian date in your custom input onchange method , line 49
> 
> ```js
> let date = new DateObject({
>     date: strDate,
>     format: "YYYY/MM/DD",
>     calendar: persian,
>     locale: persian_fa,
>   });
> ```

Thank you.

**Comment by shahabyazdi** [comment]
You're welcome.

**Comment by mahboobehsalmani** [comment]
I can't enter day of the
