### ISSUE TITLE
Multiple DateTimePicker Instances with the same State not Updating Properly

### ISSUE THREAD

**Issue by ayush-lal** [shahabyazdi/react-multi-date-picker#82]
Im running into a weird issue now where if a component has two DateTimePicker instances running under the same state - adjusting the time on Picker1 won't update Picker2 (vice versa) until a date value is changed. The onChange prop is definitely updating the state for both pickers however the picker itself isn't updating with the new values.

Example:
https://codesandbox.io/s/bold-architecture-t9r1n

https://user-images.githubusercontent.com/41420385/142761228-19e4124f-5af0-49c3-bef4-986a77f140c1.mp4

**Comment by shahabyazdi** [comment]
Hi
I apologize for the delay in replying.
The date should not be mutated when using the value for two DatePickers.

**Comment by ayush-lal** [comment]
Thanks for taking the time to look into this! Your solution works perfectly!
