### ISSUE TITLE
How can I get the time and date whenever the time changed?

### ISSUE THREAD

**Issue by alirezahmz** [shahabyazdi/react-multi-date-picker#85]
Whenever the date changes I can get the value but time changes it does not give me the changed value?!

![date-mutiple-picker](https://user-images.githubusercontent.com/64639961/144698847-4f317b81-f609-4772-a05b-e314f43a7a7e.PNG)

**Comment by shahabyazdi** [comment]
It works correctly.
Please see this sandbox and tell me if there is any problem.

https://codesandbox.io/s/competent-voice-mcz6j?file=/src/App.js

**Comment by alirezahm7** [comment]
I wanna see value on log at each time the value of time changes, but now it shows me the value when the value of time changes only the first time.

**Comment by shahabyazdi** [comment]
Oh I see !!!

**Comment by alirezahm7** [comment]
Thank you for taking the trouble to help me.I do appreciate it.

**Comment by shahabyazdi** [comment]
You're welcome.
