### ISSUE TITLE
Not able to delete selected dates directly from input.

### ISSUE THREAD

**Issue by KA-32** [shahabyazdi/react-multi-date-picker#86]
Currently I am not able to delete dates on click of backspace button in the input. Is there way to delete selected dates ?

**Comment by jamsfy-cyrus** [comment]
We can delete user input character by character with backspace.

You can add a toolbar to deselect date: [Toolbar documentation](https://shahabyazdi.github.io/react-multi-date-picker/plugins/toolbar/)

**Comment by shahabyazdi** [comment]
The input in multiple and range modes is editable now, you can do it by installing v4.0.0.
