### ISSUE TITLE
How to set default Value when using onlyYearPicker props ?

### ISSUE THREAD

**Issue by rivorizaldi** [shahabyazdi/react-multi-date-picker#89]
Hi, i want to set default value to date picker component when using 'onlyYearPicker ', but instead it set to 1970. i just curious, is this bug or maybe i miss something ?

**Comment by shahabyazdi** [comment]
```javascript
import { useState } from "react";
import DatePicker, { DateObject } from "react-multi-date-picker";

export default function Example() {
  const [value, setValue] = useState(
    new DateObject({ year: 2023, month: 2, day: 1 })
  );

  return <DatePicker onlyYearPicker value={value} onChange={setValue} />;
}

```

**Comment by rivorizaldi** [comment]
Thank you for the reply and the solution. So i still have to set full date with month and day in it, i got this issue because i directly set year value like :

` <DatePicker onlyYearPicker value={"2021"}  />`

Again thanks, i'll close this. Have a nice day.

**Comment by shahabyazdi** [comment]
You're welcome.
