### ISSUE TITLE
Allow to select multiple ranges with eachdaysinrange

### ISSUE THREAD

**Issue by kamaridesu** [shahabyazdi/react-multi-date-picker#93]
I noticed that the feature for multiple is only for single days, but when it comes to ranges you can only have one range at a time, it would be great if you could select multiple ranges and have them show each day in the range  something like this maybe
![Capturasadasd](https://user-images.githubusercontent.com/55502808/148618891-274ac953-ee0e-4d14-a41f-4d3413e302bf.PNG)

**Comment by jcelda** [comment]
Any news about this useful request?
Or maybe some workaround?
Thank you very much for this beautiful component!

**Comment by lagroms** [comment]
Hello,

I'm also interested in that feature.
I'd like to achieve something like that :

<img width="332" alt="Capture d’écran 2022-09-30 à 11 41 13" src="https://user-images.githubusercontent.com/88441919/193218025-ab68d98c-dc59-483f-aa5e-9524b4db29df.png">

**Comment by shahabyazdi** [comment]
The multiple range picker is added in v4.0.0.
Here is the documentation:
https://shahabyazdi.github.io/react-multi-date-picker/multiple-range/
