### ISSUE TITLE
How to add Range date with custom 

### ISSUE THREAD

**Issue by robertusadrian** [shahabyazdi/react-multi-date-picker#94]
I have request about range date, 
how to add range in custom plugin such us (today, yesterday, this week, last month) 

![range](https://user-images.githubusercontent.com/15336755/150736519-cbfb536a-1827-4174-aabf-cc06edf3caf5.PNG)

**Comment by shahabyazdi** [comment]
Hi.

**Comment by Linkmetal** [comment]
Nice example, I didn't find this on the docs, maybe is a good idea to put it as an example of custom plugins, being such a common use case 😁
