### ISSUE TITLE
placeholder prop not working 

### ISSUE THREAD

**Issue by jees47** [shahabyazdi/react-multi-date-picker#96]
placeholder prop not working even though its there 

` const [ingestDate, setIngestDate] = useState(null);`

                  <DatePicker
                      placeholder="From - To"
                      value={ingestDate}
                      onChange={(date) => {
                        setIngestDate(date);
                        console.log("ingest stat date", date[0].format());
                        console.log("ingest end date", date[1].format());
                      }}
                      maxDate={new DateObject()}
                      numberOfMonths={2}
                      range
                      format="MM/DD/YYYY HH:mm:ss A"
                      plugins={[<TimePicker position="bottom" />]}
                      render={<InputIcon className="form-control ml-2 " />}
                    />

**Comment by shahabyazdi** [comment]
Hi
It's because you are rendering custom input.
You need to set placeholder directly to it.

**Comment by jees47** [comment]
> Hi It's because you are rendering custom input. You need to set placeholder directly to it.

I passed it to the component like this , still not showing it, I am using  <InputIcon/> compoenent provided by react-multi-date-picker
`                       <InputIcon
                          className="form-control ml-2"
                          placeholder="From - To"
                        />`

**Comment by shahabyazdi** [comment]
I will work on it ...

**Comment by jees47** [comment]
> I will work on it ...

okay, thanks for your reply

**Comment by shahabyazdi** [comment]
fixed in v3.3.1.
