### ISSUE TITLE
DatePicker will appear behind MUI dialog

### ISSUE THREAD

**Issue by SaitamaTyler** [shahabyazdi/react-multi-date-picker#97]
Hello,
I'd like to use the DatePicker on a dialog of MUI.
https://mui.com/components/dialogs/

But a pop-upped calendar will appear behind the dialog.
How can I handle this?
You can see actual behavior in the following example.
https://codesandbox.io/s/compassionate-morning-kyhoh?file=/src/App.tsx

Thanks in advance.

**Comment by shahabyazdi** [comment]
Hi
please set zIndex prop to 2000:

https://codesandbox.io/s/vigilant-elbakyan-5slg9

**Comment by SaitamaTyler** [comment]
Thank you for your advice and the example.
It works perfectly.
I appreciate it.
