### ISSUE TITLE
Customize seperator between month name and year

### ISSUE THREAD

**Issue by iamebadi** [shahabyazdi/react-multi-date-picker#98]
Hi,
How good it would be if we could customize separator between month name and year.

sample: February, 2022 => February | 2022

Thanks in advance.

**Comment by stargt** [comment]
Formatting year and month combination on the header is required for my case.

Many cultures place the year prior to the month.
* e.g. `2022년 4월` == `April, 2022`
* e.g. `2022년 2월` ==`February, 2022`

**Comment by shahabyazdi** [comment]
@iamebadi @stargt now you can do it in v4.0.0
https://shahabyazdi.github.io/react-multi-date-picker/header/#separator-between-month-&-year

**Comment by iamebadi** [comment]
hi,Thanks Shahab

    On Sunday, April 16, 2023 at 07:42:26 AM GMT+3:30, Shahab ***@***.***> wrote:  
 
 


Closed #98 as completed.
